inferablehq/inferable

sdk-node/src/Inferable.ts
`client.templateReference` allows a reference to a template via the id. Useful when you need to reference a template that was created via the UI of some other means.
=> feat: Add template reference method

sdk-go/inferable.go, sdk-go/main_test.go, sdk-go/service.go
Retrieve clusterId from API rather than requiring it to be specified during client initialisation.
Relies on https://github.com/inferablehq/platform/pull/750
=> chore(sdk-go): Evaluate clusterId lazily

sdk-dotnet/src/API/Models.cs, sdk-dotnet/src/Inferable.cs, sdk-dotnet/src/Service.cs, sdk-dotnet/tests/Inferable.Tests/InferableTest.cs
Retrieve clusterId from API rather than requiring it to be specified during client initialisation.
Relies on https://github.com/inferablehq/platform/pull/750
=> chore(sdk-dotnet): Evaluate clusterId lazily

sdk-node/src/Inferable.test.ts, sdk-node/src/Inferable.ts, sdk-node/src/contract.ts, sdk-node/src/service.ts, sdk-node/src/tests/utils.ts
Retrieve clusterId from API rather than requiring it to be specified during client initialisation.
Relies on https://github.com/inferablehq/platform/pull/750
=> chore(sdk-node): Evaluate clusterId lazily

README.md, sdk-node/src/Inferable.test.ts, sdk-node/src/Inferable.ts, sdk-node/src/contract.ts, sdk-node/src/execute-fn.test.ts, sdk-node/src/execute-fn.ts, sdk-node/src/service.ts, sdk-node/src/types.ts
When `customerAuthContext` is available on a function call, pass this object within a second `context` argument to the handler.
=> feat(sdk-node): Auth context for functions

sdk-go/go.mod
This change updates the Go toolchain version in the sdk-go/go.mod file to adhere to the 1.N.P syntax required by Go 1.21 and later.
=> fix: Correct Go toolchain version syntax

control-plane/.env.base, control-plane/Dockerfile, control-plane/README.md, control-plane/docker-compose.dev.yml, control-plane/src/index.ts, control-plane/src/modules/auth/auth.ts, control-plane/src/utilities/env.ts
- Add local development readme section
- Add base `.env` file
- Rename `MASTER_API_SECRET` -> `MANAGEMENT_API_SECRET`
=> chore: Improve local development experience

.github/workflows/build.yml, load-tests/Dockerfile.machine, load-tests/README.md, load-tests/machine.ts, load-tests/package-lock.json, load-tests/package.json, load-tests/script.js
Creates initial [k6](https://k6.io/open-source/) load testing project.
The script currently calls Inferable with the prompt `Get the special word from the `searchHaystack` function`. The `searchHaystack` function returns `{ word: 'needle' }` and the test script validates this result is present.
This PR also adds a `validate-load-tests` [Github action](https://github.com/inferablehq/inferable/actions/runs/12099986071/job/33738109810) which runs on changes to `./load-tests` with the default configuration 1 VU / 1 iteration.
=> feat: Add initial load testing script

control-plane/src/modules/contract.ts, control-plane/src/modules/prompt-templates.test.ts, control-plane/src/modules/prompt-templates.ts, control-plane/src/modules/workflows/router.ts
Cleanup `createRun` handling of Run Configurations.
- Deprecate `run.config` object and replace with
- `run.configId`
- `run.input`
`run.input` will be merged with `initialPrompt` _regardless_ of whether or not a config is being used.
=> chore: Cleanup runConfigId / input merging

control-plane/src/modules/models/index.ts, control-plane/src/modules/workflows/agent/agent.ai.test.ts, control-plane/src/modules/workflows/agent/agent.ts, control-plane/src/modules/workflows/agent/run.ts, control-plane/src/utilities/env.ts
- Add the ability to mock model responses
- Mock model responses for load test cluster
=> feat: Add the ability to mock model responses

data-connector/README.md, examples/pg-stat-analysis/.gitignore, examples/pg-stat-analysis/README.md, examples/pg-stat-analysis/package-lock.json, examples/pg-stat-analysis/package.json, examples/pg-stat-analysis/src/index.ts
Adds an Inferable demonstration for analysing a Postgres DB and recommending index creation
```json
{
"summary": "After analyzing the database access patterns through pg_stat_statements, I've identified several potential performance improvements. The analysis shows that the most time-consuming queries are primarily related to job status updates and machine status management.",
"suggestions": [
{
"name": "Add index on jobs.executing_machine_id, status, and remaining_attempts",
"explanation": "One of the most time-consuming queries updates job status based on machine status and remaining attempts. This compound index would improve the performance of this frequently executed query.",
"impactedQueries": [
"UPDATE jobs as j SET status = $1 FROM machines as m WHERE j.status = $2 AND …
```
=> docs: Initial pg-stat-analysis project

.github/workflows/build.yml, app/README.md
Currently the deployment doesn't run in only `app` has changed as it relies on `test-control-plane`.
=> ci: Run Control Plane tests before deploy

app/components/chat/blob.tsx
Lower the blob rendering threshold to 50kb.
We can increase this in the future when we have a more efficient way of rendering.
=> chore: Lower blob threshold

.github/workflows/build.yml, data-connector/src/index.ts, data-connector/src/open-api/open-api.ts
- Add `allowedOperations` config field to Open API data connector
- Allow privacy / paranoid Mode to be set per-connector
Resolves: https://github.com/inferablehq/inferable/issues/227
=> feat: OpenAPI allow list

data-connector/Dockerfile
Do not copy local environment file in the `.env`
=> fix: Do not copy env file

data-connector/README.md, data-connector/src/graphql/README.md, data-connector/src/open-api/README.md
- Add walkthrough video to Readme
- Add callout for creating Inferable API Keys
- Mark OpenAPI and GraphQL as Experimental.
=> chore: Data Connector launch changes

control-plane/src/modules/models/index.test.ts, control-plane/src/utilities/errors.test.ts, control-plane/src/utilities/errors.ts
Ensure that Bedrock / Anthropic rate limiting exceptions are handled with retry logic.
=> feat: Retry model provider throttling

control-plane/drizzle/0190_equal_luke_cage.sql, control-plane/drizzle/meta/0190_snapshot.json, control-plane/drizzle/meta/_journal.json, control-plane/src/modules/auth/auth.test.ts, control-plane/src/modules/auth/auth.ts, control-plane/src/modules/cluster.ts, control-plane/src/modules/data.ts, control-plane/src/modules/test/util.ts, control-plane/src/modules/workflows/router.ts
Add `enable_customer_auth` flag to Cluster to allow [Customer Provided Auth](https://docs.inferable.ai/pages/auth#customer-provided-secrets) to be used without Run Configurations.
=> feat: Add `enable_customer_auth` to Cluster

control-plane/src/index.ts, control-plane/src/utilities/errors.ts
Adds `docsLink` key to error responses
=> feat: Add docLinks to error responses

control-plane/src/modules/jobs/create-job.ts, control-plane/src/modules/service-definitions.test.ts, control-plane/src/modules/service-definitions.ts, control-plane/src/modules/util.ts
=> feat: Validate cache.keyPath on registration

.github/workflows/build.yml, .github/workflows/publish.yml
Disable GH actions `cancel-in-progress` now that we have multiple projects in the repo.
Cancelling a build for one the publish packages means that the change won't be published.
https://github.com/inferablehq/inferable/actions/runs/12268350515
=> ci: Remove cancel in progress

cli/src/index.ts
Bug: When starting the CLI the notification to update the CLI appears twice.
=> fix: Remove duplicate update notifier

control-plane/package-lock.json, control-plane/package.json, control-plane/src/index.ts, control-plane/src/modules/slack/index.ts, control-plane/src/modules/slack/receiver.ts, control-plane/src/modules/workflows/metadata.test.ts, control-plane/src/modules/workflows/metadata.ts, control-plane/src/modules/workflows/router.ts, control-plane/src/utilities/env.ts
Support for triggering Runs via Slack and appending new messages from the thread.
In the absence of the `SLACK_*` environment variables the feature is not enabled.
TODO:
- Messages are not yet delivered back to Slack from the Run
- Slack app oAuth flow is not handled, currently the Bot secret is a static environment variable
=> feat: Slack Run triggering

control-plane/src/modules/auth/auth.ts, control-plane/src/modules/slack/index.test.ts, control-plane/src/modules/slack/index.ts, control-plane/src/modules/workflows/agent/run.ts, control-plane/src/modules/workflows/metadata.ts, control-plane/src/modules/workflows/notify.ts, control-plane/src/modules/workflows/queues.ts, control-plane/src/modules/workflows/router.ts, control-plane/src/modules/workflows/workflows.ts, control-plane/src/utilities/env.ts
- Allow Slack replies for direct messages
- Added some unit tests for Slack
- Adds `SLACK_AUTHORIZED_USER_EMAILS` until we support oAuth flow
Thread logic:
If the message is a new thread, A new run will be created.
If the message is in an existing thread without a run associated, a new run will be created and associated with the thread.
If the message is in an existing thread with a run associated, the existing run will be used.
=> feat: Slack replies

control-plane/src/modules/models/index.ts, control-plane/src/modules/router.ts, control-plane/src/modules/workflows/agent/nodes/model-call.test.ts, control-plane/src/modules/workflows/agent/nodes/model-call.ts, control-plane/src/modules/workflows/agent/tools/mock-function.ts, control-plane/src/modules/workflows/summarization.ts
As part of removing Zod usage for schemas, remove structured result parsing from `model.structured` and instead accept a Json schema object.
This does mean we can't return a typed result from `model.structured()` so Zod parsing is done _outside_ of this function where applicable.
=> feat: Use Json schema for model calls

control-plane/package-lock.json, control-plane/package.json, control-plane/src/modules/service-definitions.test.ts, control-plane/src/modules/service-definitions.ts, control-plane/src/modules/workflows/agent/agent.ai.test.ts, control-plane/src/modules/workflows/agent/nodes/model-call.ts, control-plane/src/modules/workflows/agent/nodes/model-output.test.ts, control-plane/src/modules/workflows/agent/nodes/model-output.ts
Removes final `zod-to-json-schema` usage as it required running an `eval` at runtime.
Instead, build the model's output schema using JsonSchema directly.
=> feat: Remove `zod-to-json-schema` usage

sdk-go/inferable_test.go, sdk-go/main_test.go, sdk-go/service.go, sdk-go/service_test.go
- Support struct **or** struct-pointer as first function arg
- Use `invopop/jsonschema`  `DoNotReference` option to denormalise `$ref` keys in json schemas
=> feat: Support pointer references

control-plane/src/modules/workflows/agent/tools/date-time.ts
Correct result format for `currentDateTime` internal tool.
=> fix: Correct datetime tool format

app/components/cluster-details.tsx
=> fix: Minor fixes to the service topology view

control-plane/src/modules/jobs/jobs.ts, control-plane/src/modules/workflows/agent/nodes/model-call.ts, control-plane/src/modules/workflows/agent/nodes/model-output.ts, control-plane/src/modules/workflows/agent/run.ts
- Introduced `getLatestJobsResultedByFunctionName` to fetch job results based on function name, service, and result type.
- By default, job results will be ingested into the context.
=> feat: Retrieve past function results for reinforcement learning

adapters/graphql-adapter/.gitignore, adapters/graphql-adapter/.npmignore, adapters/graphql-adapter/README.md, adapters/graphql-adapter/eslint.config.mjs, adapters/graphql-adapter/eslintrc.json, adapters/graphql-adapter/jest.config.js, adapters/graphql-adapter/package-lock.json, adapters/graphql-adapter/package.json, adapters/graphql-adapter/src/index.ts, adapters/graphql-adapter/src/test.ts, adapters/graphql-adapter/tsconfig.json
- Automatic registration of GraphQL queries and mutations as Inferable functions
- Converts GraphQL schema to JSON schema for type safety
- Handles context passing between Inferable and Apollo Server
- Supports both Query and Mutation operations
- Automatic introspection and schema conversion
The goal is to allow connecting graphql resolvers as tools for Inferable agents
=> feat: Implement GraphQL adapter for Apollo Server

sdk-node/src/Inferable.test.ts, sdk-node/src/Inferable.ts, sdk-node/src/execute-fn.test.ts, sdk-node/src/execute-fn.ts, sdk-node/src/util.test.ts, sdk-node/src/util.ts
- Replace `approvalRequest` with `new Interrupt("approval)` or `Interrupt.approval()`
- Interrupt's can be returned as rejection or resolution
Also removes the `client.api.createStructuredOutput` which was undocumented and unused for now.
=> feat: Update interrupt semantics

app/components/chat/prompt-textarea.tsx, app/components/chat/run-config.tsx, app/components/chat/sdk-commands.tsx
Adds `runContext` support to the start run UI.
=> feat: Allow passing run context in UI

app/app/globals.css, app/components/chat/ai-message.tsx, app/components/chat/blob.tsx, app/components/chat/template-mesage.tsx
- Added new text size classes (.text-xs, .text-sm, .text-md, .text-xl) in globals.css for better typography control.
- Adjusted text sizes in the DataSection and Blob components to use the new text size classes.
- Updated TemplateMessage component to use smaller text size for consistency.
These changes enhance the overall readability and visual hierarchy of the chat interface.
=> fix: Update text sizes in chat components and globals.css

control-plane/src/modules/jobs/jobs.ts, control-plane/src/modules/workflows/agent/nodes/model-call.ts, control-plane/src/modules/workflows/agent/nodes/model-output.ts, control-plane/src/modules/workflows/agent/run.ts
Reverts inferablehq/inferable#334
=> fix:  Revert "feat: Retrieve past function results for reinforcement learning"

control-plane/src/modules/jobs/jobs.test.ts, control-plane/src/modules/jobs/jobs.ts, control-plane/src/modules/tool-metadata.ts, control-plane/src/modules/workflows/agent/nodes/model-call.ts, control-plane/src/modules/workflows/agent/nodes/model-output.ts, control-plane/src/modules/workflows/agent/run.test.ts, control-plane/src/modules/workflows/agent/run.ts
Parse a JSON object as an anonymised string to prevent context leakage and save on the token spend.
=> fix: Add job data anonymization before passing for context enrichment

control-plane/src/modules/workflows/agent/run.ts
Previous job context formatting in #346 is causing some jobs to fail. 
Wrap it in a try catch.
https://www.hyperdx.io/search?q=%28%28level%3A%22error%22%29%29&tq=Dec+23+08%3A22%3A13+-+Dec+23+08%3A37%3A13&lid=cbee448c-cbf2-4abc-b2d7-ae56d3d8b5f6&sk=1734904952720000000&from=1734904333000&to=1734905233000
=> chore: Catch previous job context errors

app/components/chat/InvocationResult.tsx
Invocation-result component was re-defining the message type's data schema and had an additional key `createdAt`.
=> fix: Correct invocation result schema

control-plane/src/modules/workflows/router.ts
Result grounding was not actually being read from the request body
=> fix: Enable result grounding

control-plane/src/modules/calls/router.ts
Enforce 500kb max result size, results larger than this are persisted as [blobs](https://docs.inferable.ai/pages/blobs).
=> chore: Enforce 500kb maximum result size

app/app/clusters/[clusterId]/integrations/page.tsx, app/app/clusters/[clusterId]/integrations/valtown/page.tsx, app/client/contract.ts, control-plane/drizzle/0197_jazzy_solo.sql, control-plane/drizzle/meta/0197_snapshot.json, control-plane/drizzle/meta/_journal.json, control-plane/src/modules/contract.ts, control-plane/src/modules/data.ts, control-plane/src/modules/integrations/constants.ts, control-plane/src/modules/integrations/integrations.ts, control-plane/src/modules/integrations/schema.ts, control-plane/src/modules/integrations/tavily.ts, control-plane/src/modules/integrations/toolhouse.ts, control-plane/src/modules/integrations/types.ts, control-plane/src/modules/integrations/valtown.ts, control-plane/src/modules/jobs/external.ts, control-plane/src/modules/jobs/jobs.ts
Val.town integration allows the developer to use a val to register a val, and use that as a service. Vals are called by inferable via the integration pathway.
This requires more work:
=> feat: Add a val.town integration (alpha)

control-plane/src/modules/models/index.test.ts, control-plane/src/modules/models/index.ts, control-plane/src/modules/models/routing.ts, control-plane/src/modules/workflows/agent/nodes/model-call.ts, control-plane/src/modules/workflows/agent/nodes/system-prompt.ts, control-plane/src/modules/workflows/agent/overflow.test.ts, control-plane/src/modules/workflows/agent/overflow.ts, control-plane/src/modules/workflows/workflow-messages.ts
Adds `handleContextWindowOverflow` which truncates the chat history to ensure that it fits within the models context window. 
This will work through the message history removing the oldest message until it is within the context window and ensures that the history remains valid:
- Removes an `agent` message's subsequent invocation results
- Ensuring the conversation starts with a `human` message
This _only_ works on the messages that are fetched from the database (currently last 100). 
It should be a final guard to make sure what we are sending the model is not going to overflow.
Ideally we will also implement some history summarisation.
=> feat: Add message history truncation

control-plane/src/modules/calls/router.ts
Reapply #376 handling `undefined` result.
=> chore:  Re-apply oversized result handling

control-plane/src/modules/workflows/agent/overflow.ts
Bug fix
___
- Fixed message history validation to accept both 'human' and 'template' message types as the first message in the history
- Updated error logging message to accurately reflect the expanded validation criteria
- Prevents invalid truncation of template messages in the message history
___
<tr>
<td>
<details>
<summary><strong>overflow.ts</strong><dd><code>Allow template messages in message history validation</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
control-plane/src/modules/workflows/agent/overflow.ts
<li>Modified message type validation to allow both 'human' and 'template' <br>types as first message<br> <li> Updated error message to …
=> fix: Allow message history with only template message

control-plane/src/modules/auth/custom.ts, control-plane/src/modules/calls/router.ts, control-plane/src/modules/data.ts, control-plane/src/modules/jobs/create-job.ts, control-plane/src/modules/jobs/jobs.test.ts, control-plane/src/modules/jobs/persist-result.test.ts, control-plane/src/modules/jobs/persist-result.ts, control-plane/src/modules/observability/events.test.ts, control-plane/src/modules/tool-metadata.ts, control-plane/src/modules/workflows/notify.ts, control-plane/src/modules/workflows/workflows.ts
Enhancement
___
- Introduced background run ID functionality for cluster operations
- Made runId parameter mandatory in job creation to ensure proper tracking
- Integrated background run ID in various modules:
* Custom auth jobs
* Call router endpoints
* Job creation workflow
- Added utility function getClusterBackgroundRun to generate consistent background run IDs
- Updated tests to include background run ID in job creation
- Code formatting improvements and cleanup across multiple files
___
<tr>
<td>
<details>
<summary><strong>custom.ts</strong><dd><code>Add background run ID to custom auth jobs</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> feat: Integrate background run ID for cluster operations

.github/workflows/build.yml, control-plane/src/modules/workflows/router.ts
Enhancement
___
- Removed redundant validation check that required either `initialPrompt` or `configId` to be present when creating a workflow
- Simplified the request validation logic in the workflow creation endpoint
- Maintains existing authentication and access control checks
___
<tr>
<td>
<details>
<summary><strong>router.ts</strong><dd><code>Remove unnecessary workflow creation validation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
control-plane/src/modules/workflows/router.ts
<li>Removed redundant validation check for <code>initialPrompt</code> or <code>configId</code> <br>fields<br> <li> …
=> fix: Remove redundant validation for initialPrompt or configId

.github/workflows/build.yml
Enhancement
___
- Removed redundant `final-step` job from the build workflow that served no functional purpose
- The removed job was only echoing a completion message and depended on all other jobs
- Improves workflow clarity by removing unnecessary steps
___
<tr>
<td>
<details>
<summary><strong>build.yml</strong><dd><code>Remove unnecessary final step from build workflow</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/build.yml
<li>Removed redundant <code>final-step</code> job that only echoed "All jobs completed"<br> <br>
</details>
</td>
<td><a …
=> chore: Remove redundant final-step from build workflow

sdk-react/demo/TestPage.tsx, sdk-react/package-lock.json, sdk-react/package.json, sdk-react/src/hooks/useRun.ts
Enhancement
___
- Added Zod schema validation support to the useRun hook, allowing type-safe validation of run results
- Implemented generic type parameter `T extends z.ZodObject<any>` for strong typing of result schemas
- Enhanced the hook's return type to include validated result data
- Updated demo page to showcase schema validation usage with a sample schema
- Improved type definitions and added proper TypeScript generics support
- Simplified component initialization by removing redundant start function
___
<tr>
<td>
<details>
<summary><strong>TestPage.tsx</strong><dd><code>Add Zod schema validation to demo page</code>&nbsp; &nbsp; &nbsp; &nbsp; …
=> feat: Allow useRun to specify a resultSchema

control-plane/src/modules/integrations/slack/index.ts, control-plane/src/modules/integrations/types.ts
Update Slack integration's `onActivate` handler to clean up any existing Slack integrations with the same teamId.
___
Enhancement
___
- Added functionality to clean up existing Slack integrations with the same teamId during activation to prevent duplicate integrations
- Improved function naming for better code readability and maintenance:
- `getIntegrationForTeamId` → `integrationByTeam`
- `getIntegrationForClusterId` → `integrationByCluster`
- `uninstall` → `deleteNangoConnection`
- Added proper error handling and early returns in `onActivate` and `onDeactivate` handlers
- Implemented proper null checks for Slack connection IDs
___
<tr>
<td>
<details> …
=> feat: Cleanup conflicting Slack integrations

control-plane/src/modules/integrations/integrations.ts, control-plane/src/modules/integrations/slack/index.ts, control-plane/src/modules/integrations/types.ts
- Avoid circular dependency by using drizzle directly to cleanup conflicting Slack integrations.
- Handle duplicate Nango connections for the same cluster
___
___
- Fixed circular dependency issue in Slack integration cleanup by removing dependency on `upsertIntegrations`
- Improved conflict resolution by directly using database operations instead of recursive calls
- Enhanced logging for better tracking of Slack integration conflicts and cleanup
- Simplified connection management by extracting cleanup logic into a dedicated function
- Improved code organization and variable naming for better maintainability
___
<tr>
<td>
<details> …
=> fix: Correctly cleanup existing slack integrations

control-plane/src/modules/integrations/tavily.ts, control-plane/src/modules/integrations/toolhouse.ts, control-plane/src/modules/integrations/valtown.ts
Fixes Toolhouse and Tavily integrations which are currently broken as their [constant names are lowercase](https://github.com/inferablehq/inferable/blob/main/control-plane/src/modules/integrations/constants.ts) where as their registration names are not.
=> fix: Correct external service name casing

control-plane/src/modules/integrations/slack/index.ts
Move Slack approval message text to top level to alleviate warning 
```
[WARN] web-api:WebClient:5 The top-level `text` argument is missing in the request payload for a chat.postMessage call - It's a best practice to always provide a `text` argument when posting a message. The `text` is used in places where the content cannot be rendered such as: system push notifications, assistive technology such as screen readers, etc.
```
___
Enhancement
___
- Moved Slack message text content from blocks to top-level `text` property to follow Slack API best practices and resolve warnings
- Added `mrkdwn: true` flag to ensure proper markdown formatting in messages
- Simplified message structure by removing unnecessary block wrappers while maintaining the same visual output
- Changes affect both initial …
=> chore: Move Slack approval text to top level

control-plane/drizzle/0199_curious_mach_iv.sql, control-plane/drizzle/meta/0199_snapshot.json, control-plane/drizzle/meta/_journal.json
This was a missing migration from before.
___
Enhancement
___
- Enforces data integrity by ensuring workflow_id is never null in jobs table
- Sets default value of "unknown" for any existing null workflow_id entries
- Updates database schema snapshot to reflect the new constraints
___
<tr>
<td>
<details>
<summary><strong>0199_curious_mach_iv.sql</strong><dd><code>Add NOT NULL constraint to workflow_id column</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
control-plane/drizzle/0199_curious_mach_iv.sql
<li>Updates all null <code>workflow_id</code> values in jobs table to "unknown"<br> <li> Adds …
=> fix: Set default workflow_id and enforce non-null constraint

control-plane/src/modules/integrations/valtown.ts
Bug fix
___
- Added a necessary deletion step before upserting service definition in ValTown integration
- This change ensures that the service definition is in a clean state before updating
- Prevents potential issues with stale or conflicting service definitions
___
<tr>
<td>
<details>
<summary><strong>valtown.ts</strong><dd><code>Add service definition deletion before upsert</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
control-plane/src/modules/integrations/valtown.ts
<li>Added a deletion step before upserting service definition in ValTown <br>integration<br> <li> Ensures clean state before …
=> fix: Add deletion step before upserting service definition in ValTown integration

control-plane/src/modules/integrations/valtown.test.ts, control-plane/src/modules/integrations/valtown.ts
Enhancement
___
- Simplified the `valtownMetaSchema` validation schema by removing the unused `endpoint` field that was previously defined as a URL string
- Schema now only validates the `description` and `functions` fields
___
<tr>
<td>
<details>
<summary><strong>valtown.ts</strong><dd><code>Remove unused endpoint field from schema validation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
control-plane/src/modules/integrations/valtown.ts
<li>Removed unused <code>endpoint</code> field from <code>valtownMetaSchema</code> object schema <br>definition
</details>
</td>
<td><a href="https://github.com/inferablehq/inferable/pull/435/files#d …
=> fix: Remove unused endpoint' field from valtownMetaSchema

adapters/valtown-adapter/jsr.json, adapters/valtown-adapter/mod.ts
___
- Implemented a new token-based authentication system replacing the complex public key authentication:
* Removed crypto-based signature verification
* Added Bearer token validation through Authorization header
* Simplified authentication checks across all endpoints
- Enhanced logging and monitoring:
* Added detailed debug logs for request handling
* Improved error messages and request tracking
* Added function execution logging
- Improved error handling and response formatting for better debugging
- Updated package version to 0.0.10
___
<tr>
<td>
<details>
<summary><strong>mod.ts</strong><dd><code>Replace public key auth with …
=> fix: Replace public key auth with token-based system

app/app/clusters/[clusterId]/runs/page.tsx
Enhancement
___
- Simplified the runs page component by removing unnecessary code and dependencies
- Removed the `ServicesQuickstart` component and its related conditional rendering
- Eliminated unused API calls for cluster and events data
- Streamlined the component to focus on the prompt card functionality
___
<tr>
<td>
<details>
<summary><strong>page.tsx</strong><dd><code>Simplify runs page by removing redundant quickstart component</code></dd></summary>
<hr>
app/app/clusters/[clusterId]/runs/page.tsx
<li>Removed unused imports (<code>client</code>, <code>ErrorDisplay</code>, <code>ServicesQuickstart</code>, <br><code>auth</code>)<br> <li> Removed …
=> chore: Remove redundant ServicesQuickstart component from page.tsx

app/app/clusters/[clusterId]/runs/layout.tsx, app/app/clusters/[clusterId]/runs/page.tsx, app/components/cluster-runs-layout.tsx
Allows the run view to be maximized on small screens to preserve screen real-estate.
Fixes #374
___
Enhancement
___
- New ClusterRunsLayout component with responsive design
- Collapsible sidebars with minimize/maximize functionality
- Layout state persistence using localStorage
- Simplified and cleaner page structure
___
<tr>
<td>
<details>
<summary><strong>layout.tsx</strong><dd><code>Refactor layout to use centralized ClusterRunsLayout component</code></dd></summary>
<hr>
app/app/clusters/[clusterId]/runs/layout.tsx
<li>Removed direct usage of ClusterDetails and RunList components<br> <li> Simplified layout by using new ClusterRunsLayout component …
=> chore: Refactor layout to use ClusterRunsLayout component

control-plane/src/modules/contract.ts, control-plane/src/modules/data.ts, control-plane/src/modules/email/index.ts, control-plane/src/modules/integrations/slack/index.ts, control-plane/src/modules/router.ts, control-plane/src/modules/workflows/agent/agent.ai.test.ts, control-plane/src/modules/workflows/agent/nodes/model-call.test.ts, control-plane/src/modules/workflows/agent/nodes/tool-call.test.ts, control-plane/src/modules/workflows/agent/nodes/tool-call.ts, control-plane/src/modules/workflows/router.ts, control-plane/src/modules/workflows/workflow-messages.ts, control-plane/src/modules/workflows/workflows.ts, control-plane/src/utilities/cache.ts
Enhancement, Bug fix, Tests
___
- Unified message schema introduced for consistent message handling.
- Refactored message validation and parsing logic for robustness.
- Updated tests to align with the new schema and validation.
- Removed redundant logging and improved code formatting.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>8 files</summary><table>
<tr>
<td><strong>contract.ts</strong><dd><code>Introduced unified message schema for message handling.</code>&nbsp; &nbsp; </dd></td>
<td><a href="https://github.com/inferablehq/inferable/pull/456/files#diff-b5950839f91929a72fdc1a19dbd99f3c7db3032893deb18743fc93deff2e34bc">+37/-32</a>&nbsp; </td>
</tr>
<tr> …
=> chore: Refactor message types to use unified schema

control-plane/src/modules/contract.ts, control-plane/src/modules/router.ts, control-plane/src/modules/workflows/workflow-messages.ts, control-plane/src/modules/workflows/workflows.ts, sdk-react/src/contract.ts, sdk-react/src/hooks/useRun.ts
Allow `listMessages` to be used in a long or short polling capacity.
- Add `waitTime` query parameter to `listMessages` to enable long polling
- Rename `last` -> `limit`
#462 
___
Enhancement
___
- Added `waitTime` query parameter for long polling in `listMessages`.
- Renamed `last` parameter to `limit` for clarity.
- Updated related functions to support `waitTime` and `limit`.
- Adjusted SDK and hooks to align with new query parameters.
___
<tr>
<td>
<details>
<summary><strong>contract.ts</strong><dd><code>Add `waitTime` and rename `last` to `limit`</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> feat: Make listMessages polling configurable

control-plane/src/modules/workflows/agent/agent.ai.test.ts
Bug fix, Tests
___
- Added missing metadata (`id` and `createdAt`) to test messages in `agent.ai.test.ts`.
- Improved test message structure for better consistency and traceability.
- Enhanced test coverage by ensuring all test messages include metadata.
___
<tr>
<td>
<details>
<summary><strong>agent.ai.test.ts</strong><dd><code>Add metadata fields to test messages</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
control-plane/src/modules/workflows/agent/agent.ai.test.ts
<li>Added <code>id</code> and <code>createdAt</code> fields to test …
=> fix: Add missing metadata to test messages in agent.ai.test.ts

app/app/clusters/[clusterId]/settings/details/page.tsx, app/components/WorkflowList.tsx, control-plane/drizzle/0200_organic_terror.sql, control-plane/drizzle/meta/0200_snapshot.json, control-plane/drizzle/meta/_journal.json, control-plane/src/modules/auth/auth.test.ts, control-plane/src/modules/auth/auth.ts, control-plane/src/modules/auth/cluster.ts, control-plane/src/modules/auth/custom.ts, control-plane/src/modules/data.ts, control-plane/src/modules/workflows/metadata.ts, control-plane/src/modules/workflows/router.ts, control-plane/src/modules/workflows/workflows.ts
Require that a cluster's `customAuthHandler` returns an object with key `userId` (Other keys are allowed with `z.passthrough()`).
This value is used as the Run's `userId` (prefixed with `custom:`) and validated for run ownership.
This allows for tokens to be refreshed while still providing access to the existing runs by allowing the `customAuthHandler` to provide the identity.
___
- Enforced `userId` as the key for custom authentication.
- Updated `extractCustomAuthState` to use `userId` consistently.
- Added schema validation for custom authentication results.
- Removed unused `getRunCustomAuthToken` function.
___
<tr>
<td>
<details> …
=> feat: Enforce custom auth userId value

app/client/contract.ts, app/components/workflow.tsx, control-plane/src/modules/contract.ts, control-plane/src/modules/data.ts, control-plane/src/modules/email/index.ts, control-plane/src/modules/integrations/slack/index.ts, control-plane/src/modules/workflows/agent/run.ts, control-plane/src/modules/workflows/notify.ts, control-plane/src/modules/workflows/queues.ts, control-plane/src/modules/workflows/router.ts, control-plane/src/modules/workflows/tags.test.ts, control-plane/src/modules/workflows/tags.ts, control-plane/src/modules/workflows/workflows.ts, sdk-node/src/contract.ts, sdk-node/src/types.ts
Renames A Run's "metadata" to "tags" to better represent the intended usage.
For now `tags` and `metadata` will be accepted. This will be cleaned up in a future PR.
I will apply the DB table / index changes in a seperate PR.
___
Enhancement, Bug fix, Dependencies
___
- Renamed `workflow_metadata` to `run_tags` for improved clarity.
- Deprecated `metadata` in favor of `tags` across the codebase.
- Updated database schema and migrations to reflect the renaming.
- Upgraded `drizzle-kit` and `drizzle-orm` dependencies to resolve issues.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>11 files</summary><table>
<tr>
<td><strong>contract.ts</strong><dd><code>Added `tags` and deprecated …
=> feat: Rename workflow_metadata -> run_tags

control-plane/src/modules/contract.ts, control-plane/src/modules/email/index.ts, control-plane/src/modules/integrations/slack/index.ts, control-plane/src/modules/workflows/workflow-messages.ts
- Correct `unifiedMessageSchema` usage in Slack and Email modules (This was parsing the `data` key, the schema is actually for the whole object).
- Rename `unifiedMessageSchemaData` -> `unifiedMessageSchema` to avoid the same confusion
___
___
- Corrected the usage of `unifiedMessageSchema` across modules.
- Renamed `unifiedMessageDataSchema` to `unifiedMessageSchema` for clarity.
- Updated schema parsing logic to fix data handling issues.
- Adjusted related type definitions and function implementations.
___
<tr>
<td>
<details>
<summary><strong>contract.ts</strong><dd><code>Refactored and fixed `unifiedMessageSchema` in contract …
=> fix: Correct usage of unifiedMessageSchema

control-plane/src/modules/email/index.ts, control-plane/src/modules/integrations/slack/index.ts
Bug fix
___
- Corrected `userId` assignment in email module functions.
- Fixed `userId` assignment in Slack integration functions.
- Standardized `userId` format to include `clerk:` prefix.
___
<tr>
<td>
<details>
<summary><strong>index.ts</strong><dd><code>Fix userId handling in email module</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
control-plane/src/modules/email/index.ts
<li>Replaced <code>user.id</code> with <code>user.userId</code> in function calls.<br> <li> Standardized <code>userId</code> format to include …
=> fix: Corerct Clerk ID formatting in slack / email modules

control-plane/package.json, control-plane/src/modules/data.ts, control-plane/src/modules/runs/agent/agent.ai.test.ts, control-plane/src/modules/runs/agent/agent.ts, control-plane/src/modules/runs/agent/nodes/model-call.test.ts, control-plane/src/modules/runs/agent/run.test.ts, control-plane/src/modules/runs/agent/summarizer.ts, control-plane/src/modules/runs/agent/tools/cluster-internal-tools.ts, control-plane/src/modules/runs/queues.ts, control-plane/src/modules/runs/router.ts, control-plane/src/modules/timeline.ts
Resolves some agent tests issues introduced in #484
___
Bug fix, Tests
___
- Fixed naming inconsistencies by renaming `workflow` to `run`.
- Updated test cases to align with new naming conventions.
- Adjusted logging and error messages for clarity.
- Refactored code to improve readability and maintainability.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>4 files</summary><table>
<tr>
<td><strong>data.ts</strong><dd><code>Renamed `workflows` to `runs` and updated schema references.</code></dd></td>
<td><a href="https://github.com/inferablehq/inferable/pull/485/files#diff-389a480d000c3f91c0ca76b0cacd863c9db8ded03e464a9df80b7e905d233a05">+3/-2</a>&nbsp; &nbsp; &nbsp; </td>
</tr>
<tr> …
=> fix: Fix agent tests after workflow rename

app/client/contract.ts, app/components/chat/function-call.tsx, app/components/workflow.tsx, control-plane/src/bootstrap.ts, control-plane/src/modules/contract.ts, control-plane/src/modules/integrations/slack/index.ts, control-plane/src/modules/integrations/toolhouse.ts, control-plane/src/modules/jobs/create-job.ts, control-plane/src/modules/jobs/external.ts, control-plane/src/modules/jobs/jobs.test.ts, control-plane/src/modules/jobs/jobs.ts, control-plane/src/modules/jobs/router.ts, control-plane/src/modules/jobs/self-heal-jobs.ts, control-plane/src/modules/router.ts, control-plane/src/modules/runs/notify.ts, sdk-node/src/contract.ts
- Rename `/calls` -> `/jobs`
- Replace internal usage of `callId` with -> `jobId`
[This is a non-breaking change to the API as requests to `/calls` are rewritten to `/jobs` with logging.](https://github.com/inferablehq/inferable/pull/489/files#diff-8e4e22a02f3b97d06c0962b793887b30dbe788682975acdda1b012e14d42bce3R31)
___
enhancement, bug fix
___
- Rename `call` terminology to `job` across the codebase.
- Update API endpoints and internal references for consistency.
- Add request rewrite logic to maintain backward compatibility.
- Adjust tests and documentation to reflect the changes.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>13 files</summary><table>
<tr> …
=> chore: Call -> Job rename

app/components/chat/prompt-textarea.tsx, app/components/workflow.tsx
- Allow Agent's to be selected within the Playground's "Start Run" pane
- If an Agent is selected, the Run options are **not editable**
- Fix the Agent's page "Run" button which redirects to `/runs` with `agentId` query param.
https://github.com/user-attachments/assets/6f3680f2-7808-436d-bf5a-23fd3c20aea2
___
___
- Added support for selecting and triggering Agents in the Playground.
- Enhanced UI to display Agent-specific configurations and restrictions.
- Refactored `PromptTextarea` to handle Agent-specific options dynamically.
- Improved error handling and user feedback for Agent and function selection.
___
<tr>
<td>
<details> …
=> feat: Support for triggering Agent from playground

sdk-node/package.json, sdk-node/src/Inferable.test.ts, sdk-node/src/contract.ts, sdk-node/src/service.ts, sdk-node/src/tests/errors/errors.test.ts, sdk-node/src/tests/utility/caching.test.ts, sdk-node/src/tests/utility/retry.test.ts
Follow on from #489
___
Enhancement
___
- Replaced all references to "calls" with "jobs" in the Node SDK.
- Updated endpoint paths and parameter names to reflect the change.
- Adjusted descriptions and comments to align with the terminology update.
- Modified service logic to use "jobs" instead of "calls".
___
<tr>
<td>
<details>
<summary><strong>contract.ts</strong><dd><code>Refactor "calls" to "jobs" in contract definitions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
sdk-node/src/contract.ts
<li>Renamed all "calls" references to "jobs".<br> <li> Updated endpoint paths and parameter names.<br> <li> Adjusted descriptions …
=> feat: Replace calls -> jobs in node SDK

control-plane/src/modules/integrations/slack/index.test.ts, control-plane/src/modules/integrations/slack/index.ts
Tests, Enhancement
___
- Added unit tests for Slack integration cleanup logic.
- Exported `cleanupConflictingIntegrations` for external usage.
- Adjusted logging message for better clarity.
- Reordered database cleanup logic for consistency.
___
<tr>
<td>
<details>
<summary><strong>index.test.ts</strong><dd><code>Add unit tests for Slack cleanup logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
control-plane/src/modules/integrations/slack/index.test.ts
<li>Added unit tests for <code>cleanupConflictingIntegrations</code>.<br> <li> Mocked …
=> chore: Add tests around Slack cleanup logic

app/components/chat/prompt-textarea.tsx
Re-implement agent fetch in `/runs` page.
___
___
- Re-added functionality to fetch agents in the `/runs` page.
- Implemented a new `fetchAgents` function to retrieve agent data.
- Removed unused imports and cleaned up the code structure.
- Improved error handling for agent fetching with `createErrorToast`.
___
<tr>
<td>
<details>
<summary><strong>prompt-textarea.tsx</strong><dd><code>Re-implemented agent fetching and cleaned up code</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
app/components/chat/prompt-textarea.tsx
<li>Added a <code>fetchAgents</code> function to retrieve agent data.<br> <li> …
=> fix: Re-add agent tab in Runs page

control-plane/src/modules/integrations/toolhouse.ts
Now that the service timeout (#518 ) has been reduced to < the tollhouse sync job, make the toolhouse.ai integration's service `type=permanent` to avoid cleanup.
Also implement the integration's `onDeactivate` handler to allow service cleanup.
___
Enhancement
___
- Made the `toolhouse` service type permanent for persistent integration.
- Implemented `onDeactivate` handler to clean up service definitions.
- Updated service definition logic to include deletion functionality.
___
<tr>
<td>
<details>
<summary><strong>toolhouse.ts</strong><dd><code>Update ToolHouse integration for permanence and cleanup</code>&nbsp; &nbsp; </dd></summary>
<hr> …
=> feat: Make Toolhouse permanent

app/app/layout.tsx, app/instrumentation.ts, app/lib/hyperdx.ts, app/next.config.mjs, app/package-lock.json, app/package.json
Enhancement
___
- Integrates HyperDX for frontend telemetry and monitoring.
- Adds server-side and browser-side HyperDX initialization logic.
- Updates `next.config.mjs` to enable instrumentation and handle warnings.
- Includes necessary HyperDX dependencies in `package.json`.
___
<tr>
<td>
<details>
<summary><strong>instrumentation.ts</strong><dd><code>Add server-side HyperDX initialization logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
app/instrumentation.ts
<li>Implements server-side HyperDX initialization.<br> <li> Checks for <code>HYPERDX_API_KEY</code> and runtime …
=> feat: Add hyperDX for FE telemetry

control-plane/src/modules/service-definitions.ts
Bug fix
___
- Removed the throttle mechanism in `recordServicePoll` function.
- Simplified the logic for updating service poll timestamps.
- Ensured consistent behavior for database updates without throttling.
___
<tr>
<td>
<details>
<summary><strong>service-definitions.ts</strong><dd><code>Removed throttling logic in `recordServicePoll` function</code>&nbsp; </dd></summary>
<hr>
control-plane/src/modules/service-definitions.ts
<li>Removed the <code>withThrottle</code> wrapper from <code>recordServicePoll</code>.<br> <li> Simplified the function logic for database updates.<br> <li> Ensured the function directly updates the timestamp without <br>throttling. …
=> fix: Remove service poll throttle

sdk-go/interrupt.go, sdk-go/service.go
#125
Adds support for Interrupt / Approvals in Golang.
Similar to error handling, the SDK will check each of the return values for one of type `Interrupt` and persist that if applicable.
=> feat: Add support for approval requests in Go

app/components/chat/human-message.tsx, app/components/workflow.tsx
Bug fix
___
- Hide 'Edit' and 'Retry' buttons in chat component.
- Hide 'Retry' button in workflow component.
- Ensure buttons are conditionally hidden using CSS class.
___
<tr>
<td>
<details>
<summary><strong>human-message.tsx</strong><dd><code>Hide 'Edit' and 'Retry' buttons in chat</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
app/components/chat/human-message.tsx
<li>Added <code>hidden</code> class to 'Edit' button.<br> <li> Added <code>hidden</code> class to 'Retry' button.<br> <li> Ensured buttons are conditionally hidden in the chat component. …
=> fix: Hide buttons in chat and workflow components

control-plane/src/modules/auth/auth.ts, control-plane/src/modules/auth/router.ts, control-plane/src/modules/cluster.ts, control-plane/src/modules/integrations/router.ts, control-plane/src/modules/router.ts, control-plane/src/modules/runs/router.ts
- Submit "unqualified" (strip `clerk:`, etc) entity Ids to post hog so clerk sessions can be associated with FE user
- Add `is_demo` property to `api:run_create` event
- Add `api:integration_delete` / `api:integration_update` events
=> chore: Posthog improvements

control-plane/src/modules/contract.ts, control-plane/src/modules/router.ts
___
- Removed the unused `getServerStats` endpoint and method.
- Cleaned up related code in `contract.ts` and `router.ts`.
- Improved code maintainability by eliminating dead code.
___
<tr>
<td>
<details>
<summary><strong>contract.ts</strong><dd><code>Remove `getServerStats` endpoint definition</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
control-plane/src/modules/contract.ts
<li>Removed the <code>getServerStats</code> endpoint definition.<br> <li> Deleted associated response schema for server stats.
</details>
</td>
<td><a …
=> fix: Remove unused getServerStats endpoint and method

control-plane/src/modules/runs/agent/tools/calculator.ts
The logs don't seem to be being returned to the agent
=> fix: Return e2b logs in result

app/app/clusters/[clusterId]/integrations/slack/page.tsx, app/client/contract.ts, control-plane/src/modules/contract.ts, control-plane/src/modules/data.ts, control-plane/src/modules/integrations/router.ts, control-plane/src/modules/integrations/slack/index.ts
Allow Slack messages to be routed via an Agent (consistent with the email integration)
=> feat: Add Slack agentId selector

control-plane/src/modules/integrations/valtown.ts
Currently the `response.json` throws with:
```
Unexpected token '<', "<html><lin"... is not valid JSON
```
=> fix: Validate valtown response is json

sdk-react/src/hooks/useInferable.ts
Add's support for passing Context when creating Runs from the React SDK: https://docs.inferable.ai/pages/runs#context
=> feat: Allow passing context to createRun

.github/workflows/publish.yml
`sdk-react` publishing [is failing](https://github.com/inferablehq/inferable/actions/runs/12759612904).
NPM CI is failing because of `@testing-library/react-hooks@8.0.1` requires `@types/react@^16.9.0 || ^17.0.0`.
=> fix: Use ci --legacy-peer-deps for react publish

control-plane/drizzle/0209_stiff_tenebrous.sql, control-plane/drizzle/0210_tiny_katie_power.sql, control-plane/drizzle/meta/0209_snapshot.json, control-plane/drizzle/meta/0210_snapshot.json, control-plane/drizzle/meta/_journal.json, control-plane/src/modules/contract.ts, control-plane/src/modules/data.ts, control-plane/src/modules/runs/agent/run.test.ts, control-plane/src/modules/runs/agent/run.ts, control-plane/src/modules/runs/index.ts, control-plane/src/modules/runs/notify.ts, control-plane/src/modules/runs/queues.ts, control-plane/src/modules/runs/router.ts, sdk-node/src/contract.ts
Adds two new properties to `createRun.onStatusChange`: `webhook` and `statuses`.
Currently, `onStatusChange` allows for an Inferable function to be receive notification of status changes. These new fields provide a second option which is for the control plane to post results to a webhook.
`statuses` allows for a list of `Run.status` to be provided so that clients don't need to filter for "terminal" states (`done` / `failed`).
=> feat: Add webhook handler to onStatusChange

control-plane/drizzle/0211_silky_madame_hydra.sql, control-plane/drizzle/meta/0211_snapshot.json, control-plane/drizzle/meta/_journal.json, control-plane/src/modules/data.ts
Run deletion is currently broken for Runs with `external_message` records
=> fix: Cascade add onDelete to messages constraint

control-plane/src/modules/integrations/valtown.ts
Valtown uninstall was broken as it was passing in the _post_ uninstall config which was breaking the assertion
=> fix: Valtown uninstall

control-plane/src/modules/email/index.ts, control-plane/src/modules/integrations/slack/index.ts
Include `userId` and `emailAddress` in `authContext` for runs originating from Slack / Email integrations
=> feat: Include user details in authContext

control-plane/src/modules/auth/auth.ts
Include request URL in custom auth error to surface problems with the URL which are currently obfuscated by this error message.
=> chore: Include custom auth route error

sdk-node/src/Inferable.ts
This check is now redundant since the app handles it.
=> fix: streamline run creation by removing redundant getRun logic

control-plane/src/modules/contract.ts, control-plane/src/modules/runs/queues.ts, control-plane/src/modules/timeline.ts, sdk-react/src/contract.ts, sdk-react/src/hooks/useMessages.ts, sdk-react/src/hooks/useRun.test.ts, sdk-react/src/hooks/useRun.ts
- Expose Jobs via React SDK to support rendering / accepting approval requests
- Replace polling of `getMessages` with `getRunTimeline`
- Add `submitApproval` function for Job approvals
=> feat: Expose jobs via React SDK

control-plane/drizzle/0213_hesitant_pretty_boy.sql, control-plane/drizzle/meta/0213_snapshot.json, control-plane/drizzle/meta/_journal.json, control-plane/src/modules/data.ts, control-plane/src/modules/jobs/create-job.ts, control-plane/src/modules/jobs/job-results.ts, control-plane/src/modules/jobs/jobs.ts, control-plane/src/modules/jobs/self-heal-jobs.ts, control-plane/src/modules/runs/index.ts
Cleaning up old references to `workflow_id`
=> chore: Rename jobs.workflow_id to jobs.run_id

control-plane/src/modules/runs/agent/nodes/edges.ts, control-plane/src/modules/runs/index.ts
`createRun` was attempting to resume the Run _before_ the initial message had been added.
Remove the `runProcessQueue` message from `createRun` and allow this to happen when the first message is added.
Also adds more descriptive error handling.
=> fix: Remove redundant run queue resume

app/client/contract.ts, control-plane/src/modules/contract.ts, control-plane/src/modules/runs/agent/nodes/tool-call.ts, control-plane/src/modules/runs/messages.ts, sdk-react/src/contract.ts
- Add `toolName` to invocation result for easier parsing on frontend
- Add polyfill to `getRunMessagesForDisplay` to ensure that older messages have `toolName` populated
=> chore: Add toolName to invocation-result message

control-plane/src/modules/runs/agent/nodes/tool-call.ts, control-plane/src/modules/runs/messages.ts
Some cases of `invocation-result` messages do not have `toolName` set.
=> fix: Add tool name to invocation messages

control-plane/drizzle/0226_past_captain_marvel.sql, control-plane/drizzle/meta/0226_snapshot.json, control-plane/drizzle/meta/_journal.json, control-plane/src/bootstrap.ts, control-plane/src/modules/contract.ts, control-plane/src/modules/data.ts, control-plane/src/modules/router.ts, control-plane/src/modules/service-definitions.ts, control-plane/src/modules/tools/index.ts
Introduces a new 'tools' table which is decoupled from services.
The tools table will store a tool's definition *and* embedding information.
This PR adds the new table and updates `createMachine` route to start storing the tools in the new table.
Seperate PRs will be created to:
- Support polling the individual tools from the SDKs
- Update the agent function search to use the new tools table
=> feat: Introduce tools table

control-plane/src/modules/contract.ts, control-plane/src/modules/jobs/jobs.ts, control-plane/src/modules/queues/run-process.ts, control-plane/src/modules/router.ts, control-plane/src/modules/runs/agent/run.ts, control-plane/src/modules/runs/agent/tool-search.ts, control-plane/src/modules/runs/agent/tools/functions.ts, control-plane/src/modules/tools/index.ts
Follow on from new `tool` table introduced in #702
Adds support for:
- Polling jobs via individual tool name / new tools table 
- Processing jobs using the new tools table gated by `v2ToolUsage` flag
=> feat: Introduce v2 tool usage

control-plane/src/modules/tools/index.ts, control-plane/src/modules/tools/validations.ts, sdk-node/src/Inferable.test.ts, sdk-node/src/tests/errors/animals.ts, sdk-node/src/tests/errors/errors.test.ts, sdk-node/src/tests/utility/caching.test.ts, sdk-node/src/tests/utility/product.ts, sdk-node/src/tests/utility/retry.test.ts
Make tool name Restriction stricter for
[public](https://docs.inferable.ai/pages/functions#config) tools.
This is to avoid running into Claude's
[validations](https://docs.anthropic.com/en/docs/build-with-claude/tool-use#specifying-tools)
=> feat: More restrictive tool names

control-plane/drizzle/0232_awesome_tusk.sql, control-plane/drizzle/0232_narrow_paper_doll.sql, control-plane/drizzle/meta/0232_snapshot.json, control-plane/drizzle/meta/_journal.json, control-plane/src/modules/contract.ts, control-plane/src/modules/data.ts, control-plane/src/modules/queues/run-process.ts, control-plane/src/modules/router.ts, control-plane/src/modules/runs/agent/run.test.ts, control-plane/src/modules/runs/agent/run.ts, control-plane/src/modules/runs/index.ts, control-plane/src/modules/runs/simple/run.ts, control-plane/src/modules/runs/tags.ts, sdk-node/src/contract.ts, sdk-node/src/workflows/workflow.test.ts, sdk-node/src/workflows/workflow.ts
Adds a new field to `createRun`, `type=simple|agent` which specifies if a run should be multi-step (agent) or not.
```ts
const simpleCall = ctx.agent({
name: "test",
type: "simple",
systemPrompt: "Return the word, needle.",
resultSchema: z.object({
word: z.string(),
}),
});
const simpleResult = await simpleCall.trigger({
data: {},
});
```
=> feat: 'simple' Run support

control-plane/src/modules/auth/custom.ts, control-plane/src/modules/contract.ts, control-plane/src/modules/data.ts, control-plane/src/modules/jobs/jobs.test.ts, control-plane/src/modules/jobs/jobs.ts, control-plane/src/modules/router.ts, sdk-node/src/util.ts, sdk-node/src/workflows/workflow.ts
Support for `general` Interrupt type from jobs which will pause without creating an approval request.
=> chore: Support general interrupt type

control-plane/src/modules/contract.ts, control-plane/src/modules/workflows/executions.ts, sdk-node/src/util.ts, sdk-node/src/workflows/workflow.test.ts, sdk-node/src/workflows/workflow.ts
Rather than marking a workflow as `failed`, return an `interrupt` object which will pause the job.
This will allow us to monitor the status of a Workflow (Success, failure, etc) by tracking the underlying workflow's job.
=> fix: Handle workflow pause using interrupts

adapters/pgsql-adapter/Dockerfile, adapters/pgsql-adapter/README.md, adapters/pgsql-adapter/docker-entrypoint.sh, adapters/pgsql-adapter/health-check.sh, adapters/pgsql-adapter/package.json, adapters/pgsql-adapter/src/index.ts
Adds a `--test` flag to the `pgsql-adapter` script which is also used within the `health-check` command for the docker image.
=> chore: Add pgsql-adapter image health-check

sdk-node/src/workflows/workflow.ts
The docs reference the following method for triggering workflows:
```
await inferable.workflows.trigger("riskAnalysis", {
executionId: "123",
customerId: "456",
});
```
We also expose the following:
```
inferable.workflows.create(xxx).run()
```
This PR removes the second one for now.
=> chore: Remove unused workflow trigger fn

app/client/contract.ts, control-plane/src/modules/contract.ts, control-plane/src/modules/runs/agent/nodes/edges.test.ts, control-plane/src/modules/runs/agent/nodes/tool-call.test.ts, control-plane/src/modules/runs/agent/nodes/tool-call.ts, control-plane/src/modules/runs/index.test.ts, control-plane/src/modules/runs/messages.ts, sdk-node/src/contract.ts
Adds `resultType` to `invocation-result` message for easier FE type mapping.
```
"type": "invocation-result",
"data": {
"id": "01JM1B1GH281909R36ZS4YSE6F",
"toolName": "currentDateTime",
"resultType": "resolution",
"result": {
"iso8601": "2025-02-14T04:21:33.367Z",
"unix": 1739506893367
}
},
"id": "01JM1B1GHQWB74FQDHCJG15FN0",
"createdAt": "2025-02-14T04:21:33.369Z",
"metadata": null
```
=> feat: Add resultType to invocation-result messages

control-plane/src/modules/jobs/job-results.ts, control-plane/src/modules/jobs/jobs.test.ts, control-plane/src/modules/jobs/jobs.ts, control-plane/src/modules/router.ts, control-plane/src/modules/runs/notify.ts, control-plane/src/modules/workflows/executions.ts
As with [persisting Job Results](https://github.com/inferablehq/inferable/blob/e77bf6191eb300cb7dcf3ae9a0aa227a2b1bcf96/control-plane/src/modules/jobs/job-results.ts#L85), only allow an interrupt (Including approval) to be recorded in the Job is `running` and the interrupt is being submitted by the same `machineId`.
=> fix: Only accept interrupt for claimed jobs

sdk-node/src/workflows/demo.ts, sdk-node/src/workflows/workflow.test.ts, sdk-node/src/workflows/workflow.ts
Allow [retryCountOnStall or timeoutSeconds config](https://docs.inferable.ai/pages/tool-configuration#config-object) to be set when registering workflows.
=> feat: Allow tool config to be passed to workflow registration

sdk-node/src/workflows/demo.ts, sdk-node/src/workflows/workflow.test.ts, sdk-node/src/workflows/workflow.ts
Update the workflow register function to reflect the docs: `define(input, ctx)` -> `define(ctx, input)`
=> chore: Restore documented workflow handle signature

control-plane/src/modules/jobs/job-results.ts, control-plane/src/modules/jobs/jobs.test.ts, control-plane/src/modules/jobs/self-heal-jobs.ts
We have an intermittent issue with interrupted jobs (Workflow Executions) not being resumed correctly.
This PR introduces a recovery mechanism that will catch jobs that meet the following criteria:
- `status: interrupted`
- `last_updated_at : > 1 hour ago && < 5m ago`
- `approval_requested: false`
This is obviously a bit of a work around, I am `WARN` logging on each recovered job so we can try and debug the root cause.
=> feat: Implement hanging interrupt recovery

.github/workflows/e2e.yml, load-tests/README.md, load-tests/machine.ts, load-tests/package-lock.json, load-tests/package.json, load-tests/run.js, load-tests/workflow.js
Updates the E2E / Load test to include scripts for testing both a [Workflow](https://docs.inferable.ai/pages/workflows) and individual [Run](https://docs.inferable.ai/pages/runs).
The workflow test it self uses an [Agent step](https://docs.inferable.ai/pages/agents) and [Tool usage](https://docs.inferable.ai/pages/agent-tools) so it pretty much passes through the entire stack.
=> feat: Workflow load / e2e test case

control-plane/src/modules/router.ts
The resultSchema should describe an object.
This PR improves the error message when the resultSchema is, for example an array.
This is likely as the FE SDK makes it seem appropriate:
```
const agent = ctx.agent({
name: "test",
systemPrompt: "Return the words 'hello' and 'goodbye'",
resultSchema: z.array(z.string()),
})
```
=> chore: Better invalid resultSchema errors

control-plane/src/modules/tools/index.test.ts, control-plane/src/modules/tools/index.ts
It is currently possible to trigger a Workflow with a non-exact match for the name, i.e by providing a subset of the name `search` vs `searchWorkflow`.
=> fix: Do not return workflow tools without exact name match

app/app/clusters/[clusterId]/workflows/page.tsx
In order to maintain consistency with the `/execution/<id>/` page, render Jobs with `status=success` and `resultType=rejection` as failures.
=> chore: Render job rejections as failures

app/instrumentation.ts, control-plane/src/modules/observability/hyperdx.ts, control-plane/src/modules/observability/logger.ts
Disable hyperDX log collection within the application. 
Internally (Inferable cloud) now ships these logs from ECS directly.
=> chore: Disable hyperDX log collection

control-plane/package-lock.json, control-plane/package.json, control-plane/src/modules/observability/hyperdx.ts
This will increase our bills, however, we're missing some vital usage/error data that materialise at the request level currently.
This commit adds OpenTelemetry instrumentation for Redis. This allows for tracing and monitoring Redis operations, providing valuable insights into application performance and debugging.
=> fix: Instrument more API calls and Redis

control-plane/src/modules/contract.ts, control-plane/src/modules/router.ts, sdk-node/src/workflows/workflow.ts
Moves the `/l1m` endpoints introduced in #844 under the `/clusters/` route and use regular authentication strategies.
=> feat: Move l1m endpoints under /clusters

sdk-node/src/workflows/workflow.test.ts, sdk-node/src/workflows/workflow.ts
The current behaviour is confusing as the memo will run multiple times if no value is returned.
=> chore: Force memo to return a value

app/app/clusters/[clusterId]/settings/details/page.tsx, app/client/contract.ts, control-plane/drizzle/0239_reflective_puppet_master.sql, control-plane/drizzle/meta/0239_snapshot.json, control-plane/drizzle/meta/_journal.json, control-plane/src/bootstrap.ts, control-plane/src/modules/clusters/index.ts, control-plane/src/modules/clusters/management.ts, control-plane/src/modules/contract.ts, control-plane/src/modules/data.ts, control-plane/src/modules/expiration/index.ts, control-plane/src/modules/router/index.ts
Introduces per-cluster data expiration settings (not yet observed), allowing a cluster to configure an expiration for events, runs and workflow_executions.
=> feat: Per-cluster expiration config

app/app/clusters/[clusterId]/workflows/[workflowName]/executions/[executionId]/page.tsx, app/client/contract.ts, control-plane/src/modules/contract.ts, control-plane/src/modules/workflows/executions.ts
Deleted workflows will remain within the DB to ensure idempotency, if the UI views one render an explanation.
=> feat: Render workflow deleted view

control-plane/drizzle/0244_first_invaders.sql, control-plane/drizzle/0245_free_agent_zero.sql, control-plane/drizzle/0246_white_banshee.sql, control-plane/drizzle/meta/0244_snapshot.json, control-plane/drizzle/meta/0245_snapshot.json, control-plane/drizzle/meta/0246_snapshot.json, control-plane/drizzle/meta/_journal.json, control-plane/src/modules/clusters/index.ts, control-plane/src/modules/clusters/management.ts, control-plane/src/modules/data.ts, control-plane/src/modules/test/util.ts
Cleanup unused tables from schema:
- `agents`
- `services`
- `embeddings`
- `blobs`
- `versionedEntities`
=> chore: Cleanup unused tables from schema
