- .github/workflows/build.yml
- sdk-dotnet/README.md
- sdk-dotnet/src/API/APIClient.cs
- sdk-dotnet/src/API/Models.cs
- sdk-dotnet/src/Inferable.cs
- sdk-dotnet/src/Inferable.csproj
- sdk-dotnet/tests/Inferable.Tests/InferableTest.cs
- sdk-node/README.md
- sdk-node/src/Inferable.test.ts
- sdk-node/src/Inferable.ts
- sdk-node/src/create-client.ts
- sdk-node/src/index.ts
- sdk-node/src/tests/utils.ts
- sdk-node/src/types.ts
- Add support for Run Creation to the .NET SDK
- Add similar E2E tests to Node and .Net
- Standardise readme between Node and .Net
> feat: Add run creation to .NET SDK

- sdk-dotnet/README.md
- sdk-dotnet/src/API/Models.cs
- sdk-dotnet/src/Inferable.cs
- sdk-dotnet/src/Inferable.csproj
- sdk-dotnet/tests/Inferable.Tests/InferableTest.cs
```
var run = await inferable.CreateRun(new CreateRunInput
{
...
ResultSchema = JsonSchema.FromType<RunOutput>();
});
```
> feat(dotnet): Support for result schema

- README.md
- sdk-node/src/contract.ts
- sdk-node/src/execute-fn.ts
- sdk-node/src/index.ts
- sdk-node/src/service.ts
- sdk-node/src/types.ts
- sdk-node/src/util.ts
Support for the new Call Approval syntax
```
i.default.register({
name: "deleteUser",
func: (_, context) => {
console.log("Make Order Request", context);
if (!context.approved) {
return approvalRequest();
}
console.log("Make order Approved", context);
return {success: "true"}
},
description: "Deletes a user",
schema: {
input: z.object({ id: z.string() }).passthrough(),
},
});
```
> feat(sdk-node): Call Approvals

- .github/workflows/check-package-changes.yml
- sdk-node/package.json
The became out of date because of some CI issues
> chore: Bump node package version

- control-plane/drizzle/0188_shiny_thunderbolt_ross.sql
- control-plane/drizzle/meta/0188_snapshot.json
- control-plane/drizzle/meta/_journal.json
- control-plane/src/modules/data.ts
> chore: Cleanup unused tables

- control-plane/src/modules/contract.ts
- control-plane/src/modules/prompt-templates.test.ts
- control-plane/src/modules/prompt-templates.ts
- control-plane/src/modules/workflows/router.ts
Reverts inferablehq/inferable#179
> Revert "chore: Cleanup runConfigId / input merging"

- load-tests/script.js
https://github.com/inferablehq/inferable/actions/runs/12111048727/job/33762334391
> fix: Handle run pausing in load test

- control-plane/src/modules/models/index.ts
> chore: Cleanup import

- load-tests/Dockerfile.machine
- load-tests/script.js
- Update load test Dockerfile entry point
- Add more checks to load test script
> chore: Update load test entrypoint

- control-plane/src/modules/auth/api-secret.test.ts
- control-plane/src/modules/auth/api-secret.ts
- control-plane/src/modules/auth/auth.test.ts
- control-plane/src/modules/cluster.ts
- control-plane/src/modules/contract.ts
- control-plane/src/modules/customer-telemetry.ts
- control-plane/src/modules/management.ts
- control-plane/src/modules/workflows/agent/nodes/tool-call.test.ts
- control-plane/src/modules/workflows/agent/tools/cluster-internal-tools.ts
- control-plane/src/utilities/cache.ts
- Auth context cache wasn't actually being set.
- Update `createCache` to consult local `node-cache` and remote Redis
> feat: Caching improvements

- control-plane/docker-compose.dev.yml
- data-connector/README.md
- Add data connector configuration mounting example
- Remove some duplicate detail tags
- Add (commented out) data connector to development environment
> docs: Add data-connector configuration mounting

- data-connector/package-lock.json
- data-connector/package.json
- data-connector/src/index.ts
- data-connector/src/open-api/open-api.ts
> feat: Skip invalid data-connector configurations

- app/components/chat/blob.tsx
- Add a download button to Blobs
- Do not attempt to render `application/json` greater than 5mb
- Wrap blob in `Card`
> feat: Download button / limit JSON size

- app/README.md
> docs: Fix typo

- data-connector/package-lock.json
- data-connector/package.json
- data-connector/src/open-api/open-api.ts
- Support JSON / Yaml
- Support query parameters
- Support headers
- Remove `path` and `method` literals from function schemas as the model won't always provide these
- Camel case operation IDs
> fix: Various OpenAPI fixes

- app/app/clusters/[clusterId]/settings/details/page.tsx
- app/client/contract.ts
- control-plane/src/modules/contract.ts
- control-plane/src/modules/management.ts
- control-plane/src/modules/router.ts
> feat: Customer auth toggle

- sdk-react/package.json
NPM and Git package versions are out of sync.
> chore: Bump sdk-react

- sdk-node/src/index.ts
- sdk-node/src/types.ts
export `handleCustomerAuthSchema` 
https://docs.inferable.ai/pages/auth#handlecustomerauth
> chore: Expose handleCustomerAuthSchema

- app/app/clusters/[clusterId]/configs/[promptId]/edit/page.tsx
- app/app/clusters/[clusterId]/configs/new/page.tsx
- app/client/contract.ts
- app/components/chat/prompt-template-form.tsx
- app/components/workflow.tsx
- control-plane/drizzle/0191_perfect_wasp.sql
- control-plane/drizzle/meta/0191_snapshot.json
- control-plane/drizzle/meta/_journal.json
- control-plane/src/modules/contract.ts
- control-plane/src/modules/data.ts
- control-plane/src/modules/prompt-templates.ts
- control-plane/src/modules/router.ts
- control-plane/src/modules/workflows/workflow-messages.ts
- Include `invocation-result` in `listMessages` and `getRunTimeline`
- Remove `public` field from `runConfigs` (Not handled at the cluster level)
> chore: Include invocation messages

- assistant-ui/README.md
- assistant-ui/demo/TestPage.jsx
- assistant-ui/src/inferable-provider-runtime.ts
Adds the ability to register custom function UIs using the Inferable assistant-ui runtime
> feat: Support for rendering tools in Assistant UI

- control-plane/package-lock.json
- control-plane/package.json
- control-plane/src/modules/auth/customer-auth.ts
- control-plane/src/modules/service-definitions.test.ts
- control-plane/src/modules/service-definitions.ts
- Test `handleCustomerAuth` at registration time to ensure it is valid
> chore: Validate handleCustomerAuth registration

- sdk-go/inferable.go
> feat: Add Go HandleCustomerAuthInput type

- sdk-dotnet/src/Inferable.cs
> feat: Add HandleCustomerAuthInput type for .NET

- sdk-dotnet/src/Inferable.csproj
This is out of sync with Nuget
> chore: Bump sdk-dotnet

- sdk-dotnet/src/Inferable.cs
> chore: Make HandleCustomerAuthInput non-generic

- sdk-node/src/index.ts
- sdk-node/src/types.ts
- `statusChangeSchema` -> `onStatusChangeInput`
- `handleCustomerAuthSchema` -> `handleCustomerAuthInput`
Inline with c# and .Net
> chore: Rename handleCustomerAuthInput type

- connectors/assistant-ui/package-lock.json
- connectors/assistant-ui/package.json
- connectors/assistant-ui/src/inferable-provider-runtime.ts
> chore: Update useInferableRuntime authTypes

- sdk-go/inferable.go
> chore: sdk-go rename handleCustomerAuth

- sdk-node/src/index.ts
- sdk-node/src/types.ts
> chore: sdk-node rename handleCustomerAuth

- sdk-dotnet/src/Inferable.cs
> chore: sdk-dotnet rename handleCustomerAuth

- control-plane/src/modules/service-definitions.ts
Currently this overloads the "timestamp" property to introduce minimal change to the contracts on the front-end, and database schema.
We'll come back and change the schemas as needed.
This is needed for the tavily integration.
> feat: Introduce "permanent" services which are long-lived

- .github/workflows/publish.yml
This seems to be merging them currently
> ci: Clear Bootstrap Archives before re-creating them

- control-plane/src/modules/workflows/agent/run.ts
- control-plane/src/modules/workflows/agent/tools/date-time.ts
- Attach `currentDateTime` tool
- Add unix timestamp to return value
> feat: Attach timestamp tool

- app/components/chat/prompt-textarea.tsx
Update Run option descriptions and include link to docs
> docs: Update Run option descriptions

- .github/workflows/build.yml
- .husky/pre-commit
- .prettierignore
- .prettierrc
- .vscode/settings.json
- adapters/trpc-adapter/package-lock.json
- app/package-lock.json
- app/package.json
- control-plane/package-lock.json
- control-plane/package.json
- sdk-react/package-lock.json
- sdk-react/package.json
Add prettier commands that format the current diff, and improve the husky commands.
> chore: Add prettier commands to format code on PR

- app/app/clusters/[clusterId]/configs/page.tsx
- app/app/clusters/[clusterId]/runs/layout.tsx
- app/app/clusters/[clusterId]/usage/page.tsx
- app/app/layout.tsx
- app/components/breadcrumbs.tsx
- app/components/header.tsx
> feat: Playground responsiveness improvements

- app/components/header.tsx
> chore: Render playground logo on small displays

- control-plane/src/modules/workflows/agent/agent.ai.test.ts
Update Agent gets to match new result structure from #350
> fix: Update agent tests result structure

- control-plane/src/modules/calls/router.ts
Reverts inferablehq/inferable#375
> fix: revert "chore: Enforce 500kb maximum result size"

- app/app/clusters/[clusterId]/settings/details/page.tsx
- app/client/contract.ts
- control-plane/drizzle/0196_giant_boom_boom.sql
- control-plane/drizzle/0196_volatile_maginty.sql
- control-plane/drizzle/meta/0196_snapshot.json
- control-plane/drizzle/meta/_journal.json
- control-plane/src/modules/auth/custom.test.ts
- control-plane/src/modules/auth/custom.ts
- control-plane/src/modules/cluster.ts
- control-plane/src/modules/contract.ts
- control-plane/src/modules/data.ts
- control-plane/src/modules/integrations/constants.ts
- control-plane/src/modules/integrations/integrations.ts
- control-plane/src/modules/integrations/schema.ts
- control-plane/src/modules/integrations/tavily.ts
- control-plane/src/modules/integrations/toolhouse.ts
- control-plane/src/modules/integrations/val-town.ts
- control-plane/src/modules/jobs/persist-result.ts
- control-plane/src/modules/management.ts
- control-plane/src/modules/router.ts
- control-plane/src/modules/service-definitions.test.ts
- control-plane/src/modules/service-definitions.ts
- control-plane/src/utilities/cache.ts
Allow the `default_handleCustomAuth` to be configurable via cluster settings.
> feat: Allow custom auth function to be configured

- control-plane/src/modules/data.ts
Fixes https://app.rollbar.com/a/Inferable/fix/item/control-plane/143
> fix: Correct JSON key casing in data module

- app/components/breadcrumbs.tsx
- app/components/header.tsx
- app/components/live-check.tsx
- control-plane/package.json
- control-plane/src/modules/contract.ts
- control-plane/src/modules/slack/index.ts
- control-plane/src/modules/workflows/queues.ts
- control-plane/src/modules/workflows/router.ts
- control-plane/src/modules/workflows/workflow-messages.ts
- control-plane/src/modules/workflows/workflows.ts
- Support an optional `runId`
- Allow a run to be created without adding a message (for upcoming `useRun()` behaviour)
Fixes #387
> feat: Allow creating a run with a pre-determined runId

- sdk-react/package-lock.json
- sdk-react/package.json
Other
___
- Bump version of `@inferable/react` package from `0.0.10` to `0.0.11`
- Update version in both package.json and package-lock.json files
- Fix missing newline at end of package.json file
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>package-lock.json</strong><dd><code>Version bump in package-lock.json</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
sdk-react/package-lock.json
- Update package version from `0.0.10` to `0.0.11`
</details>
</td>
<td><a …
> chore: Update package version to 0.0.11

- control-plane/src/modules/calls/router.ts
Removes a warning log when a call result has no data.
___
Enhancement
___
- Removes unnecessary warning log that was triggered when a call result had no data
- Improves code clarity by removing redundant logging
- Streamlines error handling flow in the calls router
___
<tr>
<td>
<details>
<summary><strong>router.ts</strong><dd><code>Remove redundant empty call result warning</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
control-plane/src/modules/calls/router.ts
<li>Removed unnecessary warning log when call result is empty<br> <li> Simplified error handling flow by …
> chore: Remove missing result log

- sdk-react/package-lock.json
- sdk-react/package.json
Enhancement
___
- Added `prepublishOnly` npm script that runs a sequence of checks before publishing:
- Cleans the dist directory
- Checks code formatting
- Runs tests
- Builds the package
- Updated package version from `0.0.11` to `0.0.12`
- Downgraded prettier dependency from `3.2.5` to `3.4.2`
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>package-lock.json</strong><dd><code>Version bump and prettier dependency update</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
sdk-react/package-lock.json
<li>Updated package version from 0.0.11 to 0.0.12<br> <li> Downgraded prettier dependency …
> chore: Add prepublish script to sdk-react/package.json

- control-plane/package.json
- control-plane/src/modules/health.ts
- control-plane/src/utilities/constants.ts
(This is a change to kick the failed control-plane deploy)
___
Enhancement
___
- Removed unused TypeScript modules:
- `health.ts` module containing database health check functionality
- `constants.ts` module with notification function constant
- Updated package.json:
- Added descriptive summary for the control plane package
- Removed unused OpenAPI schema conversion dependency
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Code cleanup</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>health.ts</strong><dd><code>Remove unused health check module</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> chore: Remove unused health and constants modules

- control-plane/src/modules/integrations/slack/index.ts
Enhancement
___
- Added informative logging messages when activating and deactivating Slack integration
- Improved error handling by providing more specific warning messages for missing configuration
- Renamed parameter from `newConfig` to `config` for better code consistency
- Updated variable references throughout the code to match the new parameter name
___
<tr>
<td>
<details>
<summary><strong>index.ts</strong><dd><code>Enhanced logging and error handling in Slack integration</code>&nbsp; </dd></summary>
<hr>
control-plane/src/modules/integrations/slack/index.ts
<li>Added additional logging for Slack integration activation and <br>deactivation<br> <li> …
> chore: Add some additional logging to slack integration

- control-plane/src/modules/integrations/slack/index.ts
Handle Slack / Clerk auth failure with message back to Slack indicating failure.
___
Bug fix
___
- Enhances error handling by moving Slack/Clerk user authentication into a try-catch block
- Prevents unhandled exceptions when authentication fails
- Improves application stability and user experience by gracefully handling auth failures
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Error handling</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>index.ts</strong><dd><code>Improve error handling for Slack authentication</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
control-plane/src/modules/integrations/slack/index.ts
<li>Moved <code>authenticateUser</code> call inside …
> fix: Handle Clerk auth gracefully

- sdk-react/README.md
- sdk-react/demo/TestPage.tsx
- sdk-react/package-lock.json
- sdk-react/package.json
- sdk-react/src/hooks/useRun.ts
Enhancement
___
- Improved error handling in `useRun` hook by replacing callback-based approach with internal state management
- Added `error` state to hook return value for better error visibility
- Enhanced performance through memoization of `createMessage`, `requestParams`, and `result` values
- Optimized run state updates by adding change detection
- Removed `onError` callback from hook options interface
- Bumped package version to 0.0.16
___
<tr>
<td>
<details>
<summary><strong>TestPage.tsx</strong><dd><code>Remove onError callback from demo page</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> fix: Minor changes to @inferable/react for memoization and error handling

- control-plane/src/modules/calls/router.ts
- control-plane/src/modules/integrations/slack/index.ts
- control-plane/src/modules/jobs/jobs.test.ts
- control-plane/src/modules/jobs/jobs.ts
- control-plane/src/modules/workflows/notify.ts
https://github.com/user-attachments/assets/86a5b52b-5890-4cd8-886e-45c15b6332fb
Relay approval requests back to Slack and allow them to be approved / denied within the thread.
___
Enhancement
___
- Implemented Slack integration for approval requests, allowing users to approve/deny calls directly from Slack threads
- Added interactive buttons (Approve/Deny) in Slack messages for handling approvals
- Refactored approval-related functions to use `callId` instead of full objects for better parameter handling
- Added proper error handling and type checking for Slack interactions
- Implemented notification system to relay approval requests to Slack threads
- Updated tests to reflect new parameter structure and approval flow
___
<table><thead><tr><th></th><th align="left">Relevant …
> feat: Slack approvals

- control-plane/src/modules/integrations/valtown.test.ts
- control-plane/src/modules/integrations/valtown.ts
- control-plane/src/utilities/env.ts
Fixes #383
___
Enhancement
___
- Implemented HTTP request signing for Val.town API integration:
- Added HMAC-SHA256 signature generation using timestamp, method, path, and body
- Applied signing to both metadata and function execution endpoints
- Added environment configuration for Val.town HTTP signing secret
- Created test suite to validate signature generation
- Made integration functions exportable for better modularity
___
<tr>
<td>
<details>
<summary><strong>valtown.test.ts</strong><dd><code>Add tests for Val.town HTTP request signing</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary> …
> fix: Implement HTTP signing for Val.town API requests

- control-plane/src/modules/integrations/slack/index.ts
Enhancement
___
- Added fallback text support for better accessibility and compatibility
- Enhanced Slack message structure by adding a dedicated text section block
- Improved code formatting and structure for Slack message blocks
- Standardized button appearance by removing emoji flags
- Message now includes both block structure and fallback text for better display across different Slack clients
___
<tr>
<td>
<details>
<summary><strong>index.ts</strong><dd><code>Enhance Slack approval message structure and fallback text</code></dd></summary>
<hr>
control-plane/src/modules/integrations/slack/index.ts
<li>Added fallback text variable for Slack message<br> …
> fix: Include block and fallback text for approval

- sdk-node/src/index.ts
- sdk-node/src/util.ts
Enhancement
___
- Removes the deprecated `approvalRequest` function in favor of using the `Interrupt.approval()` method
- Updates exports to expose the `Interrupt` class directly instead of the deprecated function
- Improves code maintainability by removing legacy code
___
<tr>
<td>
<details>
<summary><strong>index.ts</strong><dd><code>Update exports to use Interrupt class</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
sdk-node/src/index.ts
- Replaced export of `approvalRequest` with `Interrupt` class export
</details>
</td>
<td><a …
> chore: Export interrupt.approval()

- control-plane/src/modules/integrations/valtown.ts
Bug fix
___
- Fixed private key formatting by implementing proper PEM structure with 64-character line splits
- Replaced simple string inclusion check with more robust key formatting approach
- Added temporary debug logging to verify key formatting
- Ensures consistent handling of private keys regardless of input format
___
<tr>
<td>
<details>
<summary><strong>valtown.ts</strong><dd><code>Enhance private key formatting with proper PEM structure</code>&nbsp; </dd></summary>
<hr>
control-plane/src/modules/integrations/valtown.ts
<li>Replaced simple PEM format check with proper key formatting using <br>64-character line splits<br> <li> Added temporary debug …
> fix: Correct private key formatting for consistent handling

- adapters/valtown-adapter/jsr.json
- adapters/valtown-adapter/mod.ts
- app/app/clusters/[clusterId]/integrations/valtown/page.tsx
- control-plane/package.json
- control-plane/src/modules/integrations/valtown.test.ts
- control-plane/src/modules/integrations/valtown.ts
- **feat: Introduce ValTown adapter with function registration and execution**
- **chore: Bump version to 0.0.2 in valtown-adapter**
- **feat: Enhance publicKey formatting in InferableService constructor**
- **chore: Add logging for request verification details in valtown-adapter**
- **fix: Convert request signing to use JWK format**
___
Enhancement
___
- Implemented new ValTown adapter with function registration and execution capabilities
- Converted key pair generation and handling to use JWK format throughout the system
- Added request authentication using public key verification in the adapter
- Updated test suite to support new JWK key format
- Added JSR configuration for ValTown adapter package
- Improved test configuration to better handle different test types
___ …
> fix: Convert request signing to use JWK format

- app/app/clusters/[clusterId]/integrations/valtown/page.tsx
- app/client/contract.ts
- control-plane/src/modules/contract.ts
- control-plane/src/modules/data.ts
- control-plane/src/modules/integrations/schema.ts
- control-plane/src/modules/integrations/valtown.test.ts
- control-plane/src/modules/integrations/valtown.ts
Enhancement
___
- Replaced RSA key pair authentication with simpler token-based authentication for Val.town integration
- Implemented secure token generation using UUID with 'sk-inf-val-' prefix
- Updated all API requests to use Bearer token authentication
- Modified database and schema definitions across frontend and backend
- Simplified authentication flow by removing complex cryptographic operations
- Updated UI to display and manage authentication token instead of public/private key pair
- Added new test cases for token-based authentication verification
___
<tr>
<td>
<details>
<summary><strong>page.tsx</strong><dd><code>Replace key pair auth with …
> fix: Replace key pair with token for Val.town integration

- app/app/clusters/page.tsx
- app/app/layout.tsx
- app/client/contract.ts
- app/components/chat/InvocationResult.tsx
- app/components/chat/ai-message.tsx
- app/components/clusters-table.tsx
- app/components/ui/data-table.tsx
- app/components/workflow.tsx
- control-plane/src/index.ts
- control-plane/src/modules/contract.ts
- control-plane/src/modules/jobs/jobs.ts
- control-plane/src/modules/observability/events.ts
- control-plane/src/modules/router.ts
- control-plane/src/modules/timeline.ts
- control-plane/src/modules/util.ts
- control-plane/src/modules/workflows/agent/tools/functions.ts
- control-plane/src/modules/workflows/router.ts
- control-plane/src/modules/workflows/workflow-messages.ts
- control-plane/src/modules/workflows/workflows.ts
Enhancement
___
- Implement long polling for timeline updates
- Replace cluster cards with sortable/filterable table
- Add job timeout handling and event logging
- Refactor message handling and retry logic
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>12 files</summary><table>
<tr>
<td><strong>page.tsx</strong><dd><code>Replace cluster cards with table view</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
<td><a href="https://github.com/inferablehq/inferable/pull/447/files#diff-74c9101b382505e21bd3b066e5cfdee6bbe5986b069e09d0582cfcdd02ddf85f">+4/-11</a>&nbsp; &nbsp; </td>
</tr> …
> fix: Implement long polling for timeline updates and refactor message handling

- control-plane/package-lock.json
- control-plane/package.json
- control-plane/scripts/sendTestEmail.ts
- control-plane/src/modules/email/index.test.ts
- control-plane/src/modules/email/index.ts
- control-plane/src/modules/email/test.util.ts
- control-plane/src/modules/integrations/slack/index.ts
- control-plane/src/modules/ses.ts
- control-plane/src/modules/workflows/notify.ts
Agent messages will be sent as email replies to the initial message's thread.
This _currently_ only works for the first message, we will need to keep track of the last  email's `Message-Id` in order to maintain the thread beyond the first reply.
___
Enhancement
___
- Implement email thread replies for agent messages
- Track message IDs and subjects for email threading
- Add AWS SES integration and configuration
- Update tests for email functionality
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>2 files</summary><table>
<tr>
<td><strong>index.ts</strong><dd><code>Implement email thread reply functionality for agent messages</code></dd></td>
<td><a …
> feat: Send run replies via email thread

- control-plane/scripts/sendTestEmail.ts
- control-plane/src/modules/data.ts
- control-plane/src/modules/email/index.ts
- control-plane/src/modules/email/test.util.ts
- control-plane/src/modules/integrations/slack/index.ts
- control-plane/src/modules/workflows/agent/run.ts
- control-plane/src/modules/workflows/notify.ts
- control-plane/src/modules/workflows/workflow-messages.ts
Agent messages appended to a Run which was initiated via Email will result in threaded email replies.
This involves adding an `externalReference` metadata key to `workflow_messages`. 
When a new email is received, we check for an `in-reply-to` or `references` header. 
If this header is set, we will search the Cluster's messages to see if we can find the associated run to continue.
___
Enhancement
___
- Implement email threading with reply tracking
- Add external reference handling for messages
- Standardize metadata parameter naming across modules
- Add message reference management utilities
___
<tr>
<td>
<details> …
> feat: Reply to Email initiated runs

- control-plane/src/modules/email/index.ts
Enhancement
___
- Added detailed error logging for SNS notification parsing
- Added error logging for SES message parsing failures
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Error handling</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>index.ts</strong><dd><code>Enhanced error logging for email message parsing</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
control-plane/src/modules/email/index.ts
<li>Added error logging for SNS notification message parsing failures<br> <li> Added error logging for SES message parsing failures
</details>
</td>
<td><a href="https://github.com/inferablehq/inferable/pull/452/files#diff-6338c186d160099dfc1a5bbf40f75e08318c49dfce050119dc3ce610377 …
> chore: Additional SNS failure logging

- control-plane/src/modules/email/index.ts
Parse a minimal object from SNS notification message
___
Enhancement
___
- Simplified SES message schema, removing non-essential fields
- Streamlined SNS notification schema requirements
- Kept only critical email and verification fields
- Improved code maintainability through schema reduction
___
<tr>
<td>
<details>
<summary><strong>index.ts</strong><dd><code>Simplify SES and SNS message validation schemas</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
control-plane/src/modules/email/index.ts
<li>Simplified SES message schema by removing non-essential fields like <br>timestamps, headers, and message …
> chore: Relax SNS message parsing

- control-plane/src/modules/email/index.test.ts
- control-plane/src/modules/email/index.ts
Best effort strategy for stripping email chain quotes.
___
Enhancement
___
- Strip trailing email chain quotes from messages
- Add quote stripping test coverage
- Update message handling flow
* Replace insertRunMessage with addMessageAndResume
* Simplify message data structure
___
<tr>
<td>
<details>
<summary><strong>index.test.ts</strong><dd><code>Add test for email quote stripping functionality</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
control-plane/src/modules/email/index.test.ts
<li>Added test case for email chain quote stripping functionality<br> <li> Verifies that trailing quoted text starting with '>' is …
> feat: Strip email chain quotes

- control-plane/src/modules/email/index.ts
Enhancement
___
- Add "Inferable" display name to outgoing emails
- Improve email sender format for better readability
___
<tr>
<td>
<details>
<summary><strong>index.ts</strong><dd><code>Add display name to email sender address</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
control-plane/src/modules/email/index.ts
<li>Modified email Source field to include "Inferable" display name<br> <li> Updated email sender format from simple address to RFC 5322 format
</details>
</td>
<td><a href="https://github.com/inferablehq/inferable/pull/455/files#diff-6338c186d16009 …
> chore: Include name in email address

- app/client/contract.ts
- app/components/chat/InvocationResult.tsx
- app/components/chat/ai-message.tsx
- app/components/chat/human-message.tsx
- app/components/chat/markdown.tsx
- app/components/chat/template-mesage.tsx
- app/components/chat/workflow-event.tsx
- app/components/workflow.tsx
- control-plane/src/modules/contract.ts
- control-plane/src/modules/data.ts
- control-plane/src/modules/email/index.ts
- control-plane/src/modules/integrations/slack/index.ts
- control-plane/src/modules/router.ts
- control-plane/src/modules/workflows/agent/agent.ai.test.ts
- control-plane/src/modules/workflows/agent/nodes/edges.test.ts
- control-plane/src/modules/workflows/agent/nodes/model-call.test.ts
- control-plane/src/modules/workflows/agent/nodes/model-call.ts
- control-plane/src/modules/workflows/agent/nodes/tool-call.test.ts
- control-plane/src/modules/workflows/agent/nodes/tool-call.ts
- control-plane/src/modules/workflows/agent/run.ts
- control-plane/src/modules/workflows/agent/state.ts
- control-plane/src/modules/workflows/router.ts
- control-plane/src/modules/workflows/workflow-messages.ts
- control-plane/src/modules/workflows/workflows.ts
- control-plane/src/utilities/cache.ts
Enhancement, Bug fix, Tests
___
- Unified message schema introduced for consistent message handling.
- Refactored message-related components and workflows to use the new schema.
- Improved validation and error handling for message types.
- Updated tests to align with the new unified schema.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>15 files</summary><table>
<tr>
<td><strong>contract.ts</strong><dd><code>Introduced unified message schema and refactored exports.</code></dd></td>
<td><a href="https://github.com/inferablehq/inferable/pull/459/files#diff-f9f903da20c390025ebd16471b02a8c32f82a40e10f6519a035fcfc8a4df4a4c">+61/-42</a>&nbsp; </td>
</tr>
<tr> …
> chore: Consolidate message schemas into unified structure

- control-plane/src/modules/workflows/workflow-messages.ts
Bug fix
___
- Corrected SQL query to extract `displayableContext` from metadata.
- Fixed syntax issue by adding a missing semicolon.
___
<tr>
<td>
<details>
<summary><strong>workflow-messages.ts</strong><dd><code>Fix SQL query and syntax in workflow-messages.ts</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
control-plane/src/modules/workflows/workflow-messages.ts
<li>Updated SQL query to correctly extract <code>displayableContext</code>.<br> <li> Added a missing semicolon in function parameter definition.
</details>
</td>
<td><a href="https://github.com/inferablehq/inferable/pull/465/files#diff-d30d2ee300da8f01f2a2a37 …
> fix: Correct SQL query for displayable context extraction

- sdk-node/src/contract.ts
Enhancement
___
- Added new schemas and fields for integrations and agents.
- Introduced `unifiedMessageDataSchema` for message handling.
- Replaced `run-configs` with `agents` in API paths and definitions.
- Enhanced API endpoints with additional parameters and validations.
___
<tr>
<td>
<details>
<summary><strong>contract.ts</strong><dd><code>Major updates to schemas and API definitions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
sdk-node/src/contract.ts
<li>Added <code>unifiedMessageDataSchema</code> for message handling.<br> <li> Replaced <code>run-configs</code> with …
> chore: Bump node SDK ts-rest contract

- control-plane/drizzle/0204_melodic_ikaris.sql
- control-plane/drizzle/meta/0204_snapshot.json
- control-plane/drizzle/meta/_journal.json
Commit migration for `timeout_interval_seconds` default
___
- Added a new SQL migration to set a default value for `timeout_interval_seconds` in the `jobs` table.
- Updated the metadata snapshot to reflect the new database schema changes.
- Appended a new migration entry to the journal file for tracking.
___
<tr>
<td>
<details>
<summary><strong>0204_melodic_ikaris.sql</strong><dd><code>Add SQL migration for default timeout</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
control-plane/drizzle/0204_melodic_ikaris.sql
<li>Added a SQL …
> chore: Apply un-applied migrations

- app/client/contract.ts
- control-plane/src/modules/contract.ts
- control-plane/src/modules/workflows/notify.ts
- control-plane/src/modules/workflows/router.ts
- sdk-node/package.json
- sdk-node/src/contract.ts
Follow on from #473 and #466 cleaning up deprecated fields.
___
Enhancement
___
- Removed deprecated `metadata` and `configId` fields across multiple files.
- Updated logic to use `agentId` consistently instead of `configId`.
- Simplified and cleaned up code by removing redundant warnings and checks.
- Adjusted payload and query handling to align with updated schema.
___
<tr>
<td>
<details>
<summary><strong>contract.ts</strong><dd><code>Remove deprecated fields from client contract schema</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
app/client/contract.ts
<li>Removed <code>metadata</code> and <code>configId</code> fields from the …
> chore: Cleanup `configId` and `metadata` in Run API

- app/app/clusters/[clusterId]/agents/[agentId]/edit/page.tsx
- app/client/contract.ts
- app/components/WorkflowList.tsx
- app/components/chat/template-mesage.tsx
- app/components/chat/template-message.tsx
- app/components/workflow-tab.tsx
- app/components/workflow.tsx
- control-plane/src/modules/contract.ts
- control-plane/src/modules/workflows/workflow-messages.ts
Resolve `Invalid message data. Returning supervisor message` errors by returning all `message.metadata` and parsing "displayable" fields within the FE.
___
___
- Fix incorrect routing path for agent updates.
- Replace `displayableContext` with `metadata` for message handling.
- Update UI components to reflect metadata changes.
- Improve error logging and schema validation for messages.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><details><summary>1 files</summary><table>
<tr>
<td><strong>page.tsx</strong><dd><code>Fix incorrect routing path for agent updates</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
<td><a …
> fix: Template message parsing

- sdk-dotnet/src/Inferable.cs
Enhancement
___
- Renamed `metadata` property to `tags` in `OnStatusChangeInput`.
- Updated JSON property name to align with the new naming.
___
<tr>
<td>
<details>
<summary><strong>Inferable.cs</strong><dd><code>Rename `metadata` to `tags` in `OnStatusChangeInput`</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
sdk-dotnet/src/Inferable.cs
<li>Renamed <code>metadata</code> property to <code>tags</code> in <code>OnStatusChangeInput</code>.<br> <li> Updated JSON property name from <code>metadata</code> to <code>tags</code>.
</details>
</td>
<td><a href="https://github.com/inferablehq/inferable/pull/477/files#diff-b0975eb87ab579f267511a51f8c28e2 …
> chore: Rename metadata->tags in OnStatusChangeInput

- sdk-go/inferable.go
Enhancement
___
- Renamed `Metadata` field to `Tags` in `OnStatusChangeInput`.
- Updated field name to align with new terminology.
___
<tr>
<td>
<details>
<summary><strong>inferable.go</strong><dd><code>Rename `Metadata` field to `Tags` in struct</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
sdk-go/inferable.go
<li>Renamed the <code>Metadata</code> field to <code>Tags</code> in the <code>OnStatusChangeInput</code> struct.<br> <li> Updated JSON field name from <code>metadata</code> to <code>tags</code>.
</details>
</td>
<td><a …
> chore: Rename metadata -> tags in OnStatusChangeInput

- app/app/clusters/[clusterId]/agents/layout.tsx
- app/app/clusters/[clusterId]/agents/page.tsx
- app/app/clusters/[clusterId]/integrations/page.tsx
- app/app/clusters/[clusterId]/page.tsx
- app/app/clusters/[clusterId]/runs/page.tsx
- app/app/clusters/[clusterId]/settings/layout.tsx
- app/app/clusters/[clusterId]/usage/page.tsx
- app/components/WorkflowList.tsx
- app/components/chat/ToolContextButton.tsx
- app/components/cluster-runs-layout.tsx
- app/components/create-cluster-button.tsx
- Remove hover state from non-clickable elements
- More consistent border radius in `/runs`
- Allow pages to expand to 100% width
___
___
- Improved UI consistency across multiple pages and components.
- Removed hover states from non-interactive elements.
- Enhanced layout responsiveness and alignment for better usability.
- Updated labels and descriptions for clarity and uniformity.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>10 files</summary><table>
<tr>
<td><strong>layout.tsx</strong><dd><code>Removed unnecessary text size class for layout.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
<td><a …
> feat: Minor Playground UI fixes

- app/components/workflow.tsx
___
- Fixed handling of empty responses in timeline fetch logic.
- Added retry mechanism with delays for failed fetch attempts.
- Improved timeline update logic to ensure data consistency.
- Enhanced error handling with user feedback via error toasts.
___
<tr>
<td>
<details>
<summary><strong>workflow.tsx</strong><dd><code>Refactor and enhance timeline fetch logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
app/components/workflow.tsx
<li>Adjusted logic to handle empty responses gracefully.<br> <li> Introduced retry mechanism with delays for …
> fix: Adjust timeline fetch logic to handle empty responses and errors

- app/components/chat/prompt-textarea.tsx
___
Enhancement
___
- Refactored imports for better readability and organization.
- Introduced a tab-based UI for agent and custom configurations.
- Improved code formatting and consistency across the file.
- Enhanced user experience with better error handling and UI adjustments.
___
<tr>
<td>
<details>
<summary><strong>prompt-textarea.tsx</strong><dd><code>Refactor and enhance prompt-textarea.tsx</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
app/components/chat/prompt-textarea.tsx
<li>Refactored imports for better readability.<br> <li> Added a tab-based UI …
> chore: Reformat imports and improve code readability in prompt-textarea.tsx

- sdk-dotnet/src/API/APIClient.cs
- sdk-dotnet/src/Service.cs
- sdk-dotnet/tests/Inferable.Tests/InferableTest.cs
Enhancement
___
- Replaced terminology from `calls` to `jobs` across the .NET SDK.
- Updated method names and API endpoints to reflect the change.
- Adjusted test cases to align with the new terminology.
- Improved consistency in naming conventions throughout the codebase.
___
<tr>
<td>
<details>
<summary><strong>APIClient.cs</strong><dd><code>Update API client methods and endpoints terminology</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
sdk-dotnet/src/API/APIClient.cs
<li>Renamed methods from <code>CreateCall</code> to <code>CreateJob</code> and <code>ListCalls</code> to <br><code>ListJobs</code>.<br> <li> Updated API endpoints …
> feat: Replace calls -> jobs in .NET SDK

- sdk-go/service.go
- sdk-go/service_test.go
Enhancement, Tests
___
- Replaced references to `calls` with `jobs` in the Go SDK.
- Updated API paths and error messages to reflect the change.
- Adjusted test cases to align with the new terminology.
___
<tr>
<td>
<details>
<summary><strong>service.go</strong><dd><code>Update API paths and error messages to `jobs`</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
sdk-go/service.go
<li>Updated API paths from <code>calls</code> to <code>jobs</code>.<br> <li> Adjusted error messages to use <code>jobs</code>.<br> <li> Modified method logic to align with new terminology.
</details>
</td>
<td><a …
> feat: Replace calls -> jobs in Go SDK

- app/components/chat/human-message.tsx
- control-plane/scripts/sendTestEmail.ts
- control-plane/src/modules/email/index.ts
- control-plane/src/modules/integrations/slack/index.ts
___
Enhancement
___
- Added metadata parsing to display message source in chat.
- Updated UI to show icons for message sources.
- Enhanced email and Slack integrations with metadata support.
- Commented out unused `inReplyTo` field in test script.
___
<tr>
<td>
<details>
<summary><strong>human-message.tsx</strong><dd><code>Display message source and icons in chat UI</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
app/components/chat/human-message.tsx
<li>Added metadata parsing using <code>zod</code>.<br> <li> Displayed message source (<code>via</code>) with icons in UI.<br> <li> …
> feat: Render message channel in chat

- app/components/cluster-details.tsx
- control-plane/src/modules/auth/cluster.ts
___
- Introduced a "New Service" feature in the cluster UI.
- Added functionality to create and manage API keys for services.
- Enhanced code readability and formatting consistency.
- Fixed minor issues in API key generation and validation logic.
___
<tr>
<td>
<details>
<summary><strong>cluster-details.tsx</strong><dd><code>Added "New Service" feature and UI enhancements</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
app/components/cluster-details.tsx
<li>Added a "New Service" pill and button for creating services.<br> <li> Introduced <code>CreateNewServiceOptions</code> component for …
> feat: New service command in the console

- control-plane/src/modules/email/index.ts
Updates email replies to set [in-reply-to and references](https://www.ietf.org/rfc/rfc2822.txt) headers for better email chain support in clients.
This requires us to build the email body and use SES's [SendRawEmail command](https://docs.aws.amazon.com/ses/latest/APIReference/API_SendRawEmail.html) as headers are [not configurable](https://github.com/aws/aws-sdk-js/issues/2770) in the higher level SendEmail
___
Enhancement
___
- Implemented `in-reply-to` and `references` headers for email threading.
- Replaced `sendEmail` with `sendRawEmail` for custom headers.
- Constructed MIME formatted email for better email chain support.
- Improved error handling for SES message ID response.
___
<table><thead><tr><th></th><th align="left">Relevant …
> feat: Implement in-reply-to and references headers

- app/app/clusters/[clusterId]/integrations/slack/page.tsx
Enhancement
___
- Improved import formatting for better readability.
- Refactored state initialization for `connection` variable.
- Adjusted JSX formatting for consistency and readability.
- Enhanced Slack connection UI with minor text updates.
___
<tr>
<td>
<details>
<summary><strong>page.tsx</strong><dd><code>Refactor and improve Slack integration page</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
app/app/clusters/[clusterId]/integrations/slack/page.tsx
<li>Reformatted imports for better readability.<br> <li> Refactored <code>connection</code> state initialization for …
> fix: Correct import formatting and improve code readability in Slack integration

- control-plane/src/utilities/env.ts
Bug fix
___
- Updated the default maximum database connections to 20.
- Ensures better handling of database connection limits.
___
<tr>
<td>
<details>
<summary><strong>env.ts</strong><dd><code>Update default database connection configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
control-plane/src/utilities/env.ts
<li>Changed the default value of <code>DATABASE_MAX_CONNECTIONS</code> from 10 to 20.<br> <li> Adjusted the database configuration for connection limits.
</details>
</td>
<td><a href="https://github.com/inferablehq/inferable/pull/511/files#diff-ed95a72457a1949f16d4658af91dd6270d41ce8fd9d8c415bbaf9f02 …
> fix: Update default max database connections to 20

- demos/typescript/.gitignore
- demos/typescript/LICENSE
- demos/typescript/README.md
- demos/typescript/index.ts
- demos/typescript/package-lock.json
- demos/typescript/package.json
- demos/typescript/secret.ts
- demos/typescript/sql-to-text/seed.ts
- demos/typescript/sql-to-text/service.ts
- demos/typescript/terminal-copilot/service.ts
- demos/typescript/tsconfig.json
Enhancement, Documentation
___
- Relocated TypeScript demo projects into a monorepo structure.
- Added SQL-to-text and terminal copilot services with Inferable integration.
- Included seed data setup for SQLite in-memory database.
- Provided comprehensive documentation and configuration for the demo.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>5 files</summary><table>
<tr>
<td><strong>seed.ts</strong><dd><code>Added SQLite in-memory database setup and seed data</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
<td><a href="https://github.com/inferablehq/inferable/pull/516/files#diff-bf23604194658799b32d0983d1e019d20922d9310bf8ab4861b7ce91f72aaed5">+54/-0</a>&nbsp; &nbsp; …
> chore: Relocate TypeScript demos to monorepo

- app/app/setup-demo/page.tsx
- app/client/contract.ts
- app/components/breadcrumbs.tsx
- app/components/chat/prompt-textarea.tsx
- app/components/useClusterState.ts
- control-plane/src/modules/contract.ts
- control-plane/src/modules/management.ts
- demos/typescript/sql-to-text/service.ts
___
- Removed redundant toast notifications in demo cluster setup.
- Added `isDemo` property to cluster-related data structures and components.
- Enhanced demo prompts with detailed descriptions and improved UI rendering.
- Refactored and streamlined code for better readability and maintainability.
___
<tr>
<td>
<details>
<summary><strong>page.tsx</strong><dd><code>Refactor demo cluster setup logic and notifications</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
app/app/setup-demo/page.tsx
<li>Removed redundant toast notifications during demo cluster setup.<br> <li> Improved error handling with detailed …
> fix: Remove redundant toast notifications and streamline demo cluster setup

- app/components/cluster-details.tsx
- app/components/useClusterState.ts
- app/components/workflow.tsx
- app/lib/use-hash-state.ts
- control-plane/src/modules/service-definitions.ts
- demos/typescript/sql-to-text/service.ts
- demos/typescript/terminal-copilot/service.ts
Enhancement, Bug fix, Documentation
___
- Adjusted service timeout to 1 minute for consistency.
- Enhanced UI components for better user experience and functionality.
- Improved service card and control plane box designs.
- Added "No Services Connected" UI with interactive options.
- Introduced `useHashState` for optimized state management.
- Added descriptions to service functions for better clarity.
___
<tr>
<td>
<details>
<summary><strong>cluster-details.tsx</strong><dd><code>Enhanced UI components and refactored cluster state handling</code></dd></summary>
<hr>
app/components/cluster-details.tsx
<li>Updated service card and control plane box …
> fix: Adjust service timeout to 1 minute and add descriptions to functions

- app/lib/hyperdx.ts
enhancement
___
- Disabled advanced network capture in HyperDX initialization.
- Removed console capture from HyperDX configuration.
___
<tr>
<td>
<details>
<summary><strong>hyperdx.ts</strong><dd><code>Disable advanced and console capture in HyperDX</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
app/lib/hyperdx.ts
<li>Removed <code>consoleCapture</code> from HyperDX initialization.<br> <li> Removed <code>advancedNetworkCapture</code> from HyperDX initialization.
</details>
</td>
<td><a href="https://github.com/inferablehq/inferable/pull/524/files#diff-1e191defe33109e09a390b1cb58723c18c12990546820c576496af8 …
> chore: Disable hyperdx advanced capture

- app/lib/hyperdx.ts
- Disable HyperDX replays
- Add `NEXT_PUBLIC_APP_URL` to `tracePropagationTargets`
___
enhancement
___
- Disabled HyperDX replays in the frontend.
- Added `NEXT_PUBLIC_APP_URL` to `tracePropagationTargets`.
___
<tr>
<td>
<details>
<summary><strong>hyperdx.ts</strong><dd><code>Disable replays and update trace targets in HyperDX configuration</code></dd></summary>
<hr>
app/lib/hyperdx.ts
<li>Added <code>disableReplay: true</code> to disable HyperDX replays.<br> <li> Included <code>NEXT_PUBLIC_APP_URL</code> in <code>tracePropagationTargets</code>.
</details>
</td>
<td><a href="https://github.com/inferablehq/inferable/pull/525/files#diff-1e191defe33109e09a390 …
> chore: Dissable hyperDX replays in FE

- app/components/chat/human-message.tsx
Enhancement
___
- Refactored CSS class handling using the `cn` utility function.
- Improved readability and maintainability of conditional class logic.
- Updated `pending` state logic for better UI behavior.
___
<tr>
<td>
<details>
<summary><strong>human-message.tsx</strong><dd><code>Refactor CSS class handling with `cn` utility</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
app/components/chat/human-message.tsx
<li>Replaced inline template string CSS class handling with <code>cn</code> utility.<br> <li> Simplified conditional logic for <code>pending</code> state.<br> <li> Enhanced …
> fix: Refactor CSS class handling for message component

- app/components/chat/prompt-textarea.tsx
- app/components/cluster-details.tsx
Enhancement
___
- Added demo source links for `sqlite` and `terminal` services in the cluster details.
- Updated prompt text and styling in the prompt textarea component.
- Introduced `isDemoCluster` logic to conditionally display demo-related features.
- Enhanced UI elements with improved text and button styling.
___
<tr>
<td>
<details>
<summary><strong>prompt-textarea.tsx</strong><dd><code>Update prompt text and styling for demo services</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
app/components/chat/prompt-textarea.tsx
<li>Imported <code>ExternalLinkIcon</code> from <code>lucide-react</code>.<br> <li> …
> feat: Add demo source links for sqlite and terminal services

- control-plane/src/modules/jobs/jobs.ts
- control-plane/src/modules/observability/events.ts
___
- Added event logging for job approval actions.
- Introduced new event types: `approvalRequested`, `approvalGranted`, and `approvalDenied`.
- Enhanced `requestApproval` and `submitApproval` functions to log events.
- Improved database update operations with additional returned fields.
___
<tr>
<td>
<details>
<summary><strong>jobs.ts</strong><dd><code>Enhance job approval functions with event logging</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
control-plane/src/modules/jobs/jobs.ts
<li>Added event logging for <code>requestApproval</code> and <code>submitApproval</code>.<br> <li> Introduced …
> fix: Add event logging for job approval actions

- app/app/clusters/page.tsx
- app/app/setup-demo/page.tsx
- app/components/cluster-details.tsx
- Resolves #522 (Safari API key clipboard write was failing)
- Remove a couple hover states
- Show onboarding demo view
> fix: Resolve clipboard write failure

- app/components/cluster-details.tsx
> fix: Add dialog for manual command copy on clipboard error

- app/app/clusters/[clusterId]/integrations/email/page.tsx
- app/client/contract.ts
- control-plane/src/bootstrap.ts
- control-plane/src/modules/contract.ts
- control-plane/src/modules/data.ts
- control-plane/src/modules/email/index.ts
- control-plane/src/modules/observability/events.ts
- control-plane/src/modules/runs/router.ts
- Add validate SPF / DKIM toggle for Email integration
- Reply to email thread on failure (Unauthenticated, SPF validation, etc)
> feat: Email SPF / DKIM validation

- app/client/contract.ts
- app/components/chat/human-message.tsx
- app/components/chat/template-mesage.tsx
- app/components/chat/workflow-event.tsx
- app/components/workflow.tsx
- control-plane/src/modules/contract.ts
- control-plane/src/modules/router.ts
- control-plane/src/modules/runs/messages.ts
- control-plane/src/modules/runs/router.ts
Remove Message retry and edit buttons as these are currently broken (#480). 
We may chose to re-introduce these in the future, but for now they are confusing.
> feat: Cleanup message edit APIs

- app/components/chat/ToolContextButton.tsx
> feat: Render function config in playground

- control-plane/src/modules/runs/agent/run.test.ts
- control-plane/src/modules/runs/agent/run.ts
- Correct status comparison for `onStatusChange` notification
- Adds test for calling `onStatusChange`
> fix: Correct status comparison for notify

- README.md
Documentation
___
- Revised README for improved clarity and structure.
- Added a "Quick Start" section with examples.
- Introduced "What can I build with this?" section with demos.
- Enhanced descriptions for features and SDKs.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Revise and expand README content</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
README.md
<li>Improved clarity and restructured content.<br> <li> Added "Quick Start" section with usage examples.<br> <li> …
> chore: Revise README for clarity and add new sections

- app/components/header.tsx
Enhancement
___
- Improved error handling in the authentication process.
- Enhanced `UserButton` with `signInUrl` property for better navigation.
- Updated `OrganizationSwitcher` with additional URL properties for actions.
- Minor formatting adjustments for better code readability.
___
<tr>
<td>
<details>
<summary><strong>header.tsx</strong><dd><code>Update authentication and UI component configurations</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
app/components/header.tsx
<li>Added <code>signInUrl</code> property to <code>UserButton</code> for sign-in navigation.<br> <li> Enhanced <code>OrganizationSwitcher</code> with new URL properties for …
> fix: Correct error handling in authentication process

- app/app/layout.tsx
- app/components/error-display.tsx
___
- Added a Slack help icon with a link to the navigation bar.
- Improved the `ErrorDisplay` component by simplifying code and formatting.
- Refactored humorous error messages for better readability.
- Minor UI adjustments in error display layout.
___
<tr>
<td>
<details>
<summary><strong>layout.tsx</strong><dd><code>Add Slack help icon to navigation bar</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
app/app/layout.tsx
<li>Added a Slack help icon linking to Slack community.<br> <li> Positioned the icon at the …
> fix: Integrate Slack help icon into navigation bar

- app/components/breadcrumbs.tsx
- app/components/chat/ToolContextButton.tsx
- app/components/chat/function-call.tsx
- app/components/chat/prompt-textarea.tsx
- app/components/clusters-table.tsx
___
- Enhanced navigation and usability in breadcrumbs and buttons.
- Improved error handling and user feedback in function metadata and calls.
- Added demo service prompts and examples for better onboarding.
- Refactored and optimized code for readability and maintainability.
___
<tr>
<td>
<details>
<summary><strong>breadcrumbs.tsx</strong><dd><code>Enhanced breadcrumbs with clickable links and docs.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
app/components/breadcrumbs.tsx
<li>Made cluster name clickable with hover effect.<br> <li> Added a link to external documentation.<br> <li> Improved navigation and …
> fix: Usability changes to runs

- control-plane/src/modules/management.ts
___
- Ensure unique machines in cluster details using `uniqBy`.
- Ensure unique services in cluster details using `uniqBy`.
- Refactor `getClusterDetails` to improve data consistency.
- Add lodash `uniqBy` for deduplication logic.
___
<tr>
<td>
<details>
<summary><strong>management.ts</strong><dd><code>Deduplicate machines and services in cluster details</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
control-plane/src/modules/management.ts
<li>Added <code>uniqBy</code> from lodash for deduplication.<br> <li> Ensured unique machines by filtering duplicates by <code>id</code>.<br> <li> Ensured unique services by filtering …
> fix: Ensure unique machines and services in cluster details

- app/app/clusters/[clusterId]/runs/[runId]/page.tsx
- app/app/clusters/[clusterId]/settings/details/page.tsx
- app/client/client.ts
- app/client/contract.ts
- app/components/breadcrumbs.tsx
- app/components/chat/function-call.tsx
- app/components/workflow.tsx
___
- Introduced `clientWithAbortController` to handle request cancellations.
- Refactored `Run` component to streamline timeline fetching and rendering.
- Removed redundant `fetchRunMetadata` and `mutableId` logic.
- Added abort controller for timeline fetching to prevent overlapping requests.
- Simplified `ElementWrapper` and improved memoization for timeline elements.
- Adjusted UI components for better readability and maintainability.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Miscellaneous</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>page.tsx</strong><dd><code>Removed unused client directive.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> fix: Streamline run timeline fetching and rendering

- adapters/pgsql-adapter/README.md
- adapters/pgsql-adapter/src/index.ts
Bug fix, Documentation
___
- Updated CLI options in code for consistency with documentation.
- Renamed CLI options `approvalMode` and `privacyMode` to `approval-mode` and `privacy-mode`.
- Enhanced README with detailed CLI usage examples and updated options.
- Removed outdated CLI usage section from README.
___
<tr>
<td>
<details>
<summary><strong>index.ts</strong><dd><code>Rename CLI options for consistency</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
adapters/pgsql-adapter/src/index.ts
<li>Renamed CLI options …
> fix: update CLI options in README and code for consistency

- adapters/pgsql-adapter/README.md
- adapters/valtown-adapter/README.md
- app/app/clusters/[clusterId]/integrations/page.tsx
- app/components/cluster-details.tsx
Enhancement, Documentation
___
- Enhanced UI components for better consistency and functionality.
- Updated integration configurations and removed deprecated entries.
- Improved documentation for PostgreSQL and Val.town adapters.
- Added new SDK and adapter links to the UI.
___
<tr>
<td>
<details>
<summary><strong>page.tsx</strong><dd><code>Refactor integration page and improve error handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
app/app/clusters/[clusterId]/integrations/page.tsx
<li>Updated imports for better readability and consistency.<br> <li> Removed deprecated <code>toolhouse</code> integration configuration.<br> <li> …
> chore: update README and UI components for consistency

- control-plane/src/modules/auth/auth.ts
- control-plane/src/modules/email/index.ts
- control-plane/src/modules/integrations/slack/index.ts
- control-plane/src/modules/runs/index.ts
Update Email / Slack `authContext` format
Include `userId` in `authContext`
> feat: Update auth context format

- app/components/cluster-details.tsx
- control-plane/src/bootstrap.ts
- control-plane/src/modules/analytics/index.ts
- control-plane/src/modules/runs/agent/run.ts
- control-plane/src/modules/runs/agent/tools/stdlib.ts
- control-plane/src/modules/service-definitions.ts
- control-plane/src/utilities/env.ts
Filter the standard library based on the available environment variables to better support self-hosted environments.
> feat: Filter stdlib based on environment

- app/client/contract.ts
- app/components/chat/function-call.tsx
- control-plane/src/modules/contract.ts
- control-plane/src/modules/jobs/jobs.ts
- control-plane/src/modules/jobs/router.ts
- control-plane/src/modules/router.ts
- control-plane/src/modules/service-definitions.ts
Show a "cancel" button in dashboard to allow user to kill long running jobs.
> feat: Add cancel Job button

- README.md
Reverts inferablehq/inferable#603
> Revert "chore: Remove unused demo image from README.md"

- chat-cli/README.md
- chat-cli/babel.config.js
- chat-cli/cli.tsx
- chat-cli/package-lock.json
- chat-cli/package.json
- chat-cli/src/app.tsx
- chat-cli/src/chat.tsx
- chat-cli/src/client/contract.ts
- chat-cli/src/components/AgentSelector.tsx
- chat-cli/src/components/Input.tsx
- chat-cli/src/components/RunSelector.tsx
- chat-cli/src/constants.ts
- chat-cli/src/index.ts
- chat-cli/src/lib/client.ts
- chat-cli/tsconfig.json
Initial conversational TUI package for interacting with agents via CLI.
For now, this is implemented in a seperate package `@inferabale/chat`
https://github.com/user-attachments/assets/9305fc64-393e-4be1-a0f0-bec7374f2f53
> feat: Initial Conversational TUI

- sdk-react/src/contract.ts
- sdk-react/src/hooks/useInferable.ts
- sdk-react/src/hooks/useMessages.test.ts
Allow specifying `agentId` when triggering runs from React SDK
> feat: Support agentId config

- chat-cli/package-lock.json
- chat-cli/package.json
- chat-cli/src/app.tsx
- chat-cli/src/chat.tsx
- chat-cli/src/components/Collapsible.tsx
- chat-cli/src/components/Input.tsx
- chat-cli/tsconfig.json
https://github.com/user-attachments/assets/fe1ca21b-bf27-4dc5-9e31-0bfd59cc519c
> feat: Chat TUI Expandable function calls

- control-plane/src/modules/auth/auth.ts
- control-plane/src/modules/router.ts
Allows approval requests to be resolved by API key (Cluster / Customer auth types)
Required in order to implement: https://github.com/inferablehq/inferable/pull/639
> feat: Allow approvalRequest to be resolved via API

- chat-cli/package-lock.json
- chat-cli/package.json
- chat-cli/src/chat.tsx
- chat-cli/src/components/Collapsible.tsx
Allow jobs to be approved / denied from within the chat TUI
https://github.com/user-attachments/assets/3ff1f685-864f-456a-b322-0fb5a261a097
> feat: TUI approvals

- control-plane/src/modules/management.ts
Return correct cluster ID from ephemeral cluster create endpoint
> fix: Ephemeral cluster creation

- sdk-react/src/hooks/useRun.ts
Expose `getBlobData` function via `useRun` hook
> feat: Add getBlobData to useRun hook

- control-plane/drizzle/0214_quiet_iron_patriot.sql
- control-plane/drizzle/meta/0214_snapshot.json
- control-plane/drizzle/meta/_journal.json
- control-plane/src/modules/data.ts
- control-plane/src/modules/runs/index.ts
- control-plane/src/modules/runs/tags.ts
Cleaning up old references to workflow_id
> chore: Rename workflow_metadata.workflow_id to run_id

- control-plane/drizzle/0215_useful_excalibur.sql
- control-plane/drizzle/meta/0215_snapshot.json
- control-plane/drizzle/meta/_journal.json
- control-plane/src/modules/data.ts
- control-plane/src/modules/runs/index.ts
- control-plane/src/modules/runs/messages.ts
Cleaning up old references to workflow_id
> chore: Rename message.workflow_id -> run_id

- app/client/contract.ts
- control-plane/drizzle/0216_jittery_the_hunter.sql
- control-plane/drizzle/meta/0216_snapshot.json
- control-plane/drizzle/meta/_journal.json
- control-plane/src/modules/blobs.ts
- control-plane/src/modules/contract.ts
- control-plane/src/modules/data.ts
- sdk-react/src/contract.ts
Cleaning up old references to workflow_id
> chore: Rename blob.workflow_id -> run_id

- control-plane/src/bootstrap.ts
- control-plane/src/modules/cluster.ts
Add Ephemeral cluster cleanup job (Dry run for now)
> feat: Add Ephemeral Cluster cleanup Job

- control-plane/src/modules/runs/messages.ts
- sdk-react/demo/TestPage.tsx
- sdk-react/src/hooks/useMessages.ts
- Introduced `resultMap` property to the `useMessage` options
- `resultMap` is a key-value object where key is `toolName`, value is Zod schema representing the result type
- `invocation-result` Messages returned from `useMessages` will be parsed and retain type information
- If no `resultMap` is provided all `invocation-result` messages have type `unknown`
- Any parsing error are retuned via the `error` object
This change required applying some mapping to the `invocation-result` message bodies returned via the API to remove the nested result objects which were introduced as part of the result grounding feature.
> feat: Typed `invocation-result` messages in React SDK

- control-plane/drizzle/0224_slim_klaw.sql
- control-plane/drizzle/meta/0224_snapshot.json
- control-plane/drizzle/meta/_journal.json
- control-plane/src/bootstrap.ts
- control-plane/src/modules/contract.ts
- control-plane/src/modules/cron.ts
- control-plane/src/modules/data.ts
- control-plane/src/modules/jobs/jobs.test.ts
- control-plane/src/modules/jobs/self-heal-jobs.ts
- control-plane/src/modules/router.ts
- control-plane/src/modules/runs/agent/run.test.ts
- control-plane/src/modules/runs/agent/run.ts
- control-plane/src/modules/runs/index.ts
- control-plane/src/modules/runs/notify.ts
- control-plane/src/modules/service-definitions.ts
- control-plane/src/modules/workflows/executions.test.ts
- control-plane/src/modules/workflows/executions.ts
- sdk-node/.eslintrc
- sdk-node/src/Inferable.ts
- sdk-node/src/contract.ts
- sdk-node/src/errors.ts
- sdk-node/src/service.ts
- sdk-node/src/util.ts
- sdk-node/src/util/cybr53.ts
- sdk-node/src/workflows/README.md
- sdk-node/src/workflows/demo.ts
- sdk-node/src/workflows/workflow-test-services.ts
- sdk-node/src/workflows/workflow-test-utils.ts
- sdk-node/src/workflows/workflow.test.ts
- sdk-node/src/workflows/workflow.ts
> feat: End to end workflow orchestration alpha

- app/components/chat/ai-message.tsx
- control-plane/src/modules/models/index.ts
- control-plane/src/modules/runs/agent/nodes/model-call.test.ts
- control-plane/src/modules/runs/agent/nodes/model-call.ts
- control-plane/src/modules/runs/agent/nodes/model-output.test.ts
- control-plane/src/modules/runs/agent/nodes/model-output.ts
- control-plane/src/modules/runs/agent/nodes/system-prompt.ts
> fix: Change system prompts and structured outputs for better vibes-based results.

- app/client/contract.ts
- app/components/workflow.tsx
- control-plane/src/modules/contract.ts
- control-plane/src/modules/data.ts
- control-plane/src/modules/router.ts
- control-plane/src/modules/runs/agent/nodes/model-call.ts
- control-plane/src/modules/runs/index.ts
- Added `RunSchema` to standardize run object structure across modules.
- Implemented `onStatusChangeSchema` for backward compatibility in status change handling.
- Integrated `RunSchema` in API endpoints to streamline run creation and retrieval.
- Enhanced rerun functionality in `workflow.tsx` with a new button to duplicate runs.
- Updated database schema to accommodate new run attributes.
- Improved error handling and logging for model call responses.
> feat: Introduce RunSchema and rerun functionality

- control-plane/src/modules/runs/agent/tools/functions.ts
Currently, the `tool-call` node in the Graph will create a job and poll for 5 seconds, if the job does not resolve in this time the run is paused and will be restarted when the result is received.
This PR removes the polling behaviour for a couple reasons:
- The current polling will block a queue worker for 5s while waiting for a job
- There are currently two seperate paths for job resolution handling
> chore: Remove in-process job polling

- control-plane/drizzle/0225_absurd_ben_urich.sql
- control-plane/drizzle/meta/0225_snapshot.json
- control-plane/drizzle/meta/_journal.json
- control-plane/src/modules/data.ts
https://www.hyperdx.io/search?q=%28%28level%3A%22error%22%29+AND+%28service%3A%22control-plane%22%29%29&from=1738608600000&to=1738616400000&tq=Feb+4+05%3A20%3A00+-+Feb+4+07%3A30%3A00
> chore: Replace systemPrompt varchar with text

- control-plane/src/modules/contract.ts
- control-plane/src/modules/jobs/create-job.ts
- control-plane/src/modules/jobs/jobs.ts
- control-plane/src/modules/router.ts
- control-plane/src/modules/tools/index.ts
- control-plane/src/modules/tools/validations.ts
Required to allow testing of SDK changes in #713
> chore: Use V2 tools for createJob route

- control-plane/src/modules/router.ts
- control-plane/src/modules/tools/index.ts
- control-plane/src/modules/tools/validations.ts
- control-plane/src/modules/workflows/executions.ts
Support for using V2 tools as backing for Workflow execution (gated behind flag).
> chore: Support V2 tools for Workflows

- sdk-node/README.md
- sdk-node/src/Inferable.test.ts
- sdk-node/src/Inferable.ts
- sdk-node/src/contract.ts
- sdk-node/src/execute-fn.ts
- sdk-node/src/index.ts
- sdk-node/src/polling.ts
- sdk-node/src/tests/errors/animals.ts
- sdk-node/src/tests/errors/errors.test.ts
- sdk-node/src/tests/utility/caching.test.ts
- sdk-node/src/tests/utility/product.ts
- sdk-node/src/tests/utility/retry.test.ts
- sdk-node/src/types.ts
- sdk-node/src/workflows/workflow-test-services.ts
- sdk-node/src/workflows/workflow.test.ts
- sdk-node/src/workflows/workflow.ts
- Updates Node SDK to use new tool registration format: `client.default.reguister()` -> `client.tools.register()`
- Update Node SDK to use new "tool-based" polling #707
> feat: Node SDK v2 tools support

- app/client/contract.ts
- app/components/WorkflowList.tsx
- app/components/chat/ToolContextButton.tsx
- app/components/chat/function-call.tsx
- app/components/cluster-details.tsx
- app/components/cluster-runs-layout.tsx
- app/components/workflow-tab.tsx
- app/components/workflow.tsx
- control-plane/src/modules/contract.ts
- control-plane/src/modules/cron.ts
- control-plane/src/modules/router.ts
- control-plane/src/modules/runs/index.ts
- sdk-node/src/workflows/demo.ts
> fix: Fix the UI for workflows

- app/app/clusters/[clusterId]/integrations/page.tsx
> chore: Hide unsupported integrations

- app/client/contract.ts
- app/components/chat/ToolContextButton.tsx
- app/components/chat/function-call.tsx
- app/components/chat/prompt-textarea.tsx
- app/components/cluster-details.tsx
- app/components/useClusterState.ts
- app/lib/utils.ts
- control-plane/src/modules/contract.ts
- control-plane/src/modules/cron.ts
- control-plane/src/modules/data.ts
- control-plane/src/modules/management.ts
- control-plane/src/modules/router.ts
- control-plane/src/modules/tools/index.ts
- sdk-node/src/workflows/demo.ts
- sdk-node/tsconfig.json
- **fix: uncomment mutex locking in cron registration**
- **fix: Make services into tools**
> fix: Migrate listServices -> listTools

- sdk-node/src/workflows/workflow.test.ts
- sdk-node/src/workflows/workflow.ts
Support for attaching tools to workflow agents
```
const identifyUserAgent = ctx.agent({
name: `identifyUser`,
systemPrompt: [
`You are given an email body`,
`Analyze the email and identify the user and the purpose of the email`,
],
tools: ["users_getUserByEmail"],
});
```
> feat: Agent tool attachment

- sdk-node/src/workflows/demo.ts
- sdk-node/src/workflows/workflow.ts
> feat: Implement ctx.result for at-least-once side-effect execution in workflows

- app/components/cluster-details.tsx
- control-plane/src/modules/tools/index.ts
- sdk-node/src/workflows/workflow.ts
Reverts inferablehq/inferable#751
> Revert "fix: Update workflow name delimiters from dot to underscore"

- app/app/clusters/[clusterId]/workflows/[workflowName]/[executionId]/page.tsx
- app/app/clusters/[clusterId]/workflows/[workflowName]/page.tsx
- app/app/clusters/[clusterId]/workflows/page.tsx
- app/client/contract.ts
- app/components/workflow-timeline.tsx
- control-plane/src/modules/contract.ts
- control-plane/src/modules/observability/events.test.ts
- control-plane/src/modules/observability/events.ts
- control-plane/src/modules/router.ts
- control-plane/src/modules/timeline.ts
- control-plane/src/modules/workflows/executions.ts
- sdk-node/src/Inferable.ts
- sdk-node/src/index.ts
- sdk-node/src/types.ts
- sdk-node/src/workflows/workflow.ts
> feat: Workflow approval UI

- app/app/clusters/[clusterId]/workflows/[workflowName]/[executionId]/page.tsx
- app/app/clusters/[clusterId]/workflows/[workflowName]/page.tsx
- app/app/clusters/[clusterId]/workflows/page.tsx
- app/client/contract.ts
- app/components/workflow-timeline.tsx
- control-plane/src/modules/contract.ts
- control-plane/src/modules/tools/index.ts
- control-plane/src/modules/workflows/executions.ts
- sdk-node/src/Inferable.ts
- sdk-node/src/workflows/workflow.ts
- Render debug events
- Show workflow failure in timeline
- Add description to workflow registrations
- Poll for new workflow events
> feat: Workflow view improvements

- app/app/clusters/[clusterId]/workflows/[workflowName]/[executionId]/page.tsx
> feat: Render workflow results

- app/components/chat/human-message.tsx
- Collapse large instruction UI
- Re-introduce via Slack / Email icons
> feat: Collapse large instruction UI

- sdk-node/src/errors.ts
https://github.com/inferablehq/inferable/issues/790
> chore: Looser parsing of inferable API errors

- app/app/clusters/[clusterId]/workflows/[workflowName]/executions/[executionId]/page.tsx
- sdk-node/src/Inferable.ts
> feat: Render Workflow timeout events

- app/app/clusters/[clusterId]/workflows/page.tsx
- app/components/workflow-trigger-modal.tsx
- app/package-lock.json
- app/package.json
- control-plane/src/modules/router.ts
Adds a UI for triggering workflows manually within the console
https://github.com/user-attachments/assets/8cb47213-8df8-4148-bae7-1b89e82caaaf
> feat: Manual Workflow trigger UI

- control-plane/src/modules/workflows/executions.ts
Currently, when `createWorkflowExecution` is triggered with an existing `executionId`, a new job is created even though a new WorkflowExecution is not.
For now, validate the existence of the `executionId` first. 
Longer term, this should all be in one transaction. See comment.
> fix: Validate workflow-execution before creation

- control-plane/src/modules/observability/logger.ts
- control-plane/src/modules/queues/core.ts
- control-plane/src/utilities/env.ts
Introduce an optional `ENABLE_QUEUE_INGESTION` variable that enables queue ingestion.
> feat: Seperate queue workloads

- control-plane/src/modules/cron.test.ts
- control-plane/src/modules/cron.ts
Replaces the existing cron implementation with BullMQ for improved reliability, persistence, and observability. This change introduces BullMQ queues and workers to manage scheduled jobs, ensuring retry mechanisms and graceful shutdown.
> feat: Implement cron jobs using BullMQ job scheduler

- app/app/clusters/[clusterId]/workflows/[workflowName]/executions/[executionId]/page.tsx
- app/client/contract.ts
- control-plane/drizzle/0235_mute_zodiak.sql
- control-plane/drizzle/meta/0235_snapshot.json
- control-plane/drizzle/meta/_journal.json
- control-plane/src/modules/contract.ts
- control-plane/src/modules/data.ts
Update the date handling in the cluster kv.
> fix: Update date handling in cluster_kv and contract definitions

- control-plane/src/modules/workflows/executions.ts
- sdk-node/src/workflows/workflow.ts
Rename ctx.memo to cache and handle side effects.
> feat: Introduce ctx.memo instead of ctx.result

- .husky/pre-commit
- .prettierrc
- sdk-node/.husky/pre-commit
- sdk-node/src/contract.ts
- Changed pre-commit script to execute prettier on staged files only.
- Updated prettier configuration to enforce trailing commas and adjust print width.
> chore: Update pre-commit hooks

- app/app/clusters/[clusterId]/workflows/[workflowName]/executions/[executionId]/page.tsx
- app/client/contract.ts
- control-plane/src/modules/contract.ts
- control-plane/src/modules/workflows/executions.ts
> chore: Rename results memos in api

- sdk-node/src/Inferable.ts
- sdk-node/src/eval/promptfoo.ts
Reverts inferablehq/inferable#888
> Revert "chore: Remove unused tools method from Node.js SDK"

- control-plane/src/modules/integrations/slack/index.ts
- control-plane/src/modules/integrations/slack/receiver.ts
Fixes issue introduced in #2390
> fix: Re-introduce Slack receiver for approvals

- app/app/clusters/[clusterId]/workflows/[workflowName]/executions/[executionId]/page.tsx
- app/components/event-details.tsx
> feat: Render events in Workflow view

- app/app/layout.tsx
- app/components/mobile-block-screen.tsx
- app/tailwind.config.ts
> chore: Mobile block screen
